#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

menv_export QUILT_PATCHES="debian/patches"
menv_export QUILT_REFRESH_ARGS="--backup --diffstat --strip-trailing-whitespace --no-timestamps --no-index --sort -p1 -p ab"
menv_export QUILT_DIFF_ARGS="--no-timestamps --sort --color=auto -p ab"
menv_export QUILT_DIFF_OPTS="-p --show-c-function"
menv_export QUILT_MAIL_ARGS='--from "David Bond <mokon@mokon.net>" --sender mokon@mokon.net'

menv_function quilt_graph
function quilt_graph {
  local graphdot=`mktemp --suffix=.dot`
  quilt graph --all --lines &> $graphdot
  mopen $graphdot
  rm $graphdot
}

menv_function quilt_check_build_at_each_stage
function quilt_check_build_at_each_stage {
  local MAKE='debuild -uc -us -b -i -d'
  local RC=0

  mkdir -p logs/pass
  mkdir -p logs/fail

  local PATCH=${1}
  while : ; do
    /bin/rm debian/source/format

    quilt push ${PATCH} >> logs/push.log
    quilt push >> logs/push.log
    RC=$?
    [ ${RC} -ne 0 ] && echo "Quilt Push Complete or Failure" && break

    PATCH=`quilt top`
    local FPATCH=`basename ${PATCH}`
    echo "Applied ${PATCH}"

    ${MAKE} &> logs/${FPATCH}.log
    RC=$?
    if [ ${RC} -ne 0 ] ; then
      mv logs/${FPATCH}.log logs/fail/${FPATCH}.log
    else
      mv logs/${FPATCH}.log logs/pass/${FPATCH}.log
    fi
    quilt pop -a >> logs/pop.log
    git clean -dxf -e logs >> logs/clean.log
  done;

  echo "3.0 (quilt)" &> debian/source/format
}
