#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

$BINMKDIR -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim \
 https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
