#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

$BINMKDIR -p ~/.vim/autoload ~/.vim/bundle
fetch \
  https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim \
  ~/.vim/autoload/pathogen.vim
