#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

cd ~/.vim/bundle
github_fetch scrooloose/nerdtree
github_fetch myusuf3/numbers.vim
github_fetch airblade/vim-gitgutter
#github_fetch scrooloose/syntastic

cd ~/.vim
github_fetch Rip-Rip/clang_complete
$BINMV clang_complete/bin .
$BINMV clang_complete/plugin .
$BINRM -rf clang_complete
github_fetch antoyo/vim-licenses
$BINMV vim-licenses/licenses .
$BINRM -rf vim-licenses

cd ~/.vim/plugin

fetch http://cscope.sourceforge.net/cscope_maps.vim
#fetch http://www.vim.org/scripts/download_script.php?src_id=19933 svndiff.vim
fetch http://www.yang-central.org/twiki/pub/Main/YangTools/yang.vim
fetch https://raw.githubusercontent.com/antoyo/vim-licenses/master/plugin/licenses.vim
