#!/bin/bash
# (C) 2018 David 'Mokon' Bond, All Rights Reserved

spushd .

cd $menv_cache_dir

file=http://upload.cppreference.com/mwiki/images/1/1d/html_book_20180311.tar.xz

fetch $file

extract $(basename $file)
$BINRM -f $(basename $file)

spopd
