#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~
  
safe_symlink .gdbinit $menv_dotfiles_dir/gdbinit

mkidr -p $menv_cache_dotfiles_dir/gdb
cd $menv_cache_dotfiles_dir/gdb
fetch https://sourceware.org/ml/gdb/2008-02/msg00064/stl-views.gdb

spopd
