#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

cd ~
  
safe_symlink .gdbinit $menv_dotfiles_dir/gdbinit

mkdir -p $menv_cache_dotfiles_dir/gdb
cd $menv_cache_dotfiles_dir/gdb
fetch https://sourceware.org/ml/gdb/2008-02/msg00064/stl-views.gdb
