#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

cd ~

safe_symlink .gitconfig $menv_dotfiles_dir/gitconfig
gitVersion=$(git --version | awk -F"version " '{print $2}')
if version_le $gitVersion "1.7.11" ; then
  git config --global push.default upstream
fi

cd $menv_cache_bin_dir

gitv=$(git --version)
gitv=${gitv/git version /}
curl -Os  https://raw.githubusercontent.com/git/git/v${gitv}/contrib/completion/git-completion.bash

mkdir git
cd git

git clone -q https://github.com/ejwa/gitinspector
git clone -q https://github.com/ddksr/cliist

cd ..

ln -s git/gitinsepctor/gitinspector/gitinspector.py gitinspector
ln -s git/cliist/cliist.py cliist
