#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~

safe_symlink .gitconfig $menv_dotfiles_dir/gitconfig
gitVersion=$(git --version | awk -F"version " '{print $2}')
if version_le $gitVersion "1.7.11" ; then
  git config --global push.default upstream
fi

# Let's install these cool ruby scripts for working with git!
#   http://git-wt-commit.rubyforge.org/
fetch https://gitorious.org/willgit/mainline/archive-tarball/master
tar -xvf master.tar &> /dev/null

if [ -d willgit-mainline/bin/* ] ; then
  $BINCP  willgit-mainline/bin/* $menv_cache_bin_dir
fi

if [ -d willgit-mainline ] ; then
  $BINRM -rf willgit-mainline
fi
$BINRM master.tar

cd $menv_cache_bin_dir

curl -Os https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

mkdir git
cd git

git clone -q https://github.com/ejwa/gitinspector
git clone -q https://github.com/ddksr/cliist

cd ..

ln -s git/gitinsepctor/gitinspector/gitinspector.py gitinspector
ln -s git/cliist/cliist.py cliist

fetch https://raw.githubusercontent.com/Mokon/git_get/master/git_get
chmod +x git_get

spopd
