#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

spushd .

cd $menv_cache_bin_dir
fetch http://www.yang-central.org/twiki/pub/Main/YangTools/rfcstrip
chmod +x rfcstrip

github_fetch tpope/vim-fugitive

spopd
