#!/bin/bash
# (C) 2015-2017 David 'Mokon' Bond, All Rights Reserved

if [ $MENV_DESKTOP -ne 0 ] ; then
  export GOPATH=$menv_cache_go_dir
  export PATH="$PATH:$menv_cache_go_bin_dir"
  go get github.com/schachmat/wego

  echo "To use wego add an api key to wegorc"
  safe_symlink .wegorc $menv_dotfiles_dir/wegorc
fi
