#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function cpp_class {
  local class=$1

  local year=`date +"%Y"`
  
  cat << EOF > ${class}.hpp
/* Copyright (C) $year David 'Mokon' Bond,  All Rights Reserved */

#pragma once

namespace mnet {

class $class
{
  public:
    $class() = default;
    virtual ~$class() = default;
    $class(const $class&) = delete;
    $class& operator=(const $class&) = delete;
    $class(const $class&&) = delete;
    $class& operator=(const $class&&) = delete;
};

}

EOF

  cat << EOF > ${class}.cpp
/* Copyright (C) $year David 'Mokon' Bond,  All Rights Reserved */

#include "${class}.hpp"

namespace mnet {

$class::$class() {
}

}

EOF
}

alias playground="git clone https://github.com/mokon/playground ; cd playgrround"
alias fcgi_install="sudo make install && sudo service lighttpd restart"
alias remake="make clean-purge && ./bootstrap && ./configure && make"
