#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function linecount {
  function count_ext {
    local ret=`find . -not -name "*designer.cs" -and -name "*.$1"\
      -exec wc -l {} \; \
      | awk '{lines += $1 ; files += 1  }; END { print lines } '`

    if [[ $ret == "" ]] ; then
      echo "0"
    else
      echo $ret
    fi
  }

  local HLC=`count_ext h $1`
  local CLC=`count_ext c $1`
  local CPPLC=`count_ext cpp $1`
  local CUCLC=`count_ext C $1`
  local HPPLC=`count_ext hpp $1`
  local CSLC=`count_ext cs $1`
  local JAVALC=`count_ext java $1`
  local SMLLC=`count_ext sml $1`
  unset count_ext

  echo -ne "Line Counts:\n
    C headers = $HLC, C source = $CLC\n
    C++ (CPP) source = $CPPLC, C++ (C) source = $CUCLC, C++ headers = $HPPLC\n
    C# = $CSLC, java = $JAVALC, sml = $SMLLC\n"
  local TLC=`expr $HLC + $CLC + $CPPLC + $CUCLC + $HPPLC + $CSLC + $JAVALC + $SMLLC`
  echo "Total Line Count: $TLC"
}
