#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function which_perl_module {
  echo 'print map { sprintf( "%20s : %s\n", $_, $INC{$_} ) } 
    sort keys %INC; print "\n'$1' version : $'$1'::VERSION\n\n"' | perl "-M$1"
}
