#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

menv_function run_all_tests
function run_all_tests {
  local dir=${1:-.}
  local pattern=${2:-"*Test*"}

  find $dir -type f -executable -name $pattern -and -not -name "*\.so*" -exec '{}' \;
}

menv_function sum_gtest_times
function sum_gtest_times {
    local log=$1

    cat $log | /usr/bin/grep "\[==========\]" | /usr/bin/grep total \
        | awk '{print $9}'| cut -c2- | awk '{s+=$1} END {print s/1000/60}'
}
