#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

if [ $DIST == "centos" ] ; then
  alias centos_empty_trash='/bin/rm -rf ~/.local/share/Trash/'

  if [ $PKG_MGMT == "yum" ] ; then
    alias list_packages_i_installed="yumdb search reason user"

    function list_packages_in_repo {
      local repo=$1

      yum --disablerepo='*' --enablerepo="$repo" list available
    }

    alias show_yum_vars="python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'"
  elif [ $PKG_MGMT == "dnf" ] ; then
    function list_packages_in_repo {
      local repo=$1

      dnf repo-pkgs $repo list available
    }
  fi
fi
