#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

menv_function install_java
function install_java {
  spushd

  local jrerpm=jre-8u40-linux-x64.rpm
  local jdkrpm=jdk-8u40-linux-x64.rpm
  local jrepkg=jre1.8.0_40-1.8.0_40-fcs.x86_64

  if rpm -q $jrepkg &> /dev/null ; then
    sudo rpm -e --quiet $jrepkg &> /dev/null
  fi

  fetch http://javadl.sun.com/webapps/download/AutoDL?BundleId=104759 $jrerpm
  wget -q -N --timeout=3 --tries=3 --no-check-certificate --no-cookies \
    --header "Cookie: oraclelicense=accept-securebackup-cookie" \
    http://download.oracle.com/otn-pub/java/jdk/8u40-b26/$jdkrpm

  sudo rpm -ivh --quiet $jrerpm &> /dev/null
  sudo rpm -ivh --quiet $jdkrpm &> /dev/null
  sudo $BINRM $jrerpm
  sudo $BINRM $jdkrpm

  function jaltinstall {
    if [ -f $1 ] ; then
      sudo alternatives --install $@
      if ! sudo alternatives --set $2 $3 &> /dev/null; then
        if [ -f /usr/bin/$2 ] ; then
          sudo rm /usr/bin/$2
        fi

        if [ -f /var/lib/alternatives/$2 ] ; then
          sudo rm /var/lib/alternatives/$2
        fi

        sudo alternatives --set $2 $3
      fi
    fi
  }

  jaltinstall /usr/bin/java java /usr/java/latest/bin/java 200000
  #jaltinstall /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
  jaltinstall /usr/lib/mozilla/plugins/libjavaplugin.so libjavaplugin.so /usr/java/latest/lib/i386/libnpjp2.so 200000
  jaltinstall /usr/lib64/mozilla/plugins/libjavaplugin.so libjavaplugin.so.x86_64 /usr/java/latest/lib/amd64/libnpjp2.so 200000
  jaltinstall /usr/bin/javac javac /usr/java/latest/bin/javac 200000
  jaltinstall /usr/bin/jar jar /usr/java/latest/bin/jar 200000

  spopd
}

if [ $MENV_DESKTOP -ne 0 ] ; then

read -t 5 -p "Do you want to install packages MENV might use? " -n 1 -r
echo
REPLY_PKGS=$REPLY

if [[ $REPLY_PKGS =~ ^[Yy]$ ]] ; then

menv_function create_yum_dnf_repos
function create_yum_dnf_repos {
  cat << EOF | sudo tee /etc/yum.repos.d/google-chrome.repo &> /dev/null
[google-chrome]
name=google-chrome-\$basearch
baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
EOF

  cat << EOF | sudo tee /etc/yum.repos.d/adobe-linux-x86_64.repo &> /dev/null
[adobe-linux-x86_64]
name=Adobe Systems Incorporated
baseurl=http://linuxdownload.adobe.com/linux/x86_64/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
EOF

  cat << EOF | sudo tee /etc/yum.repos.d/google-earth.repo &> /dev/null
[google-earth]
name=google-earth
baseurl=http://dl.google.com/linux/earth/rpm/stable/x86_64
enabled=1
gpgcheck=1
EOF

  cat << EOF | sudo tee /etc/yum.repos.d/jitsi.repo &> /dev/null
[jitsi]
name=Jitsi
baseurl=https://download.jitsi.org/jitsi/rpm/
enabled=1
gpgcheck=0
EOF


  cat << EOF | sudo tee /etc/yum.repos.d/rpm-sphere.repo &> /dev/null
[rpm-sphere]
name=RPM Sphere
baseurl=http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_23/
gpgkey=http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_23/repodata/repomd.xml.key
enabled=1
gpgcheck=1
EOF
}


  if [ $DIST == "fedora" ] ; then
    install_simple_package libXv.i686
    install_simple_package libXScrnSaver.i686
    install_simple_package qt.i686
    install_simple_package qt-x11.i686
    install_simple_package pulseaudio-libs.i686
    install_simple_package pulseaudio-libs-glib2.i686
    install_simple_package alsa-plugins-pulseaudio.i686
    install_simple_package qtwebkit.i686

    create_yum_dnf_repos

    if [ "$PKG_MGMT" == "yum" ] ; then

      sudo yum localinstall -q --nogpgcheck \
        http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
        http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
        | grep -v "already installed and latest version"

      sudo yum update -q -y

      fetch http://www.skype.com/go/getskype-linux-beta-fc10 skype.rpm
      sudo yum -y -q localinstall skype.rpm | grep -v "already installed and latest version"
      $BINRM skype.rpm
    fi

    if [ "$PKG_MGMT" == "dnf" ] ; then
      sudo dnf install \
        https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
        https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
        | grep -v "already installed and latest version"

      sudo dnf update -q -y

      fetch http://www.skype.com/go/getskype-linux-beta-fc10 skype.rpm
      sudo dnf -y -q localinstall skype.rpm | grep -v "already installed and latest version"
      $BINRM skype.rpm
    fi

    install_simple_package plymouth-theme*

    install_java
  fi

  install_simple_package ntpdate
  install_simple_package sed
  install_simple_package wireshark
  install_simple_package wireshark-gnome
  install_simple_package wget
  install_simple_package grep
  install_simple_package openssh-clients
  install_simple_package python-fabulous
  install_simple_package bleachbit
  install_simple_package gdmap
  install_simple_package gimp
  install_simple_package vlc
  install_simple_package google-chrome-stable
  install_simple_package cmatrix
  install_simple_package eclipse-jdt
  install_simple_package lynx
  install_simple_package time
  install_simple_package inkscape
  install_simple_package psmisc
  install_simple_package dbus-x11
  install_simple_package festival
  install_simple_package speech-dispatcher-utils
  install_simple_package espeak
  install_simple_package smem
  install_simple_package htop
  install_simple_package rdesktop
  install_simple_package simple-mtpfs
  install_simple_package libmtp
  install_simple_package fuse
  install_simple_package fuse-libs
  install_simple_package gvfs-mtp
  install_simple_package fbterm
  install_simple_package clang
  install_simple_package clang-devel
  install_simple_package tmux
  install_simple_package screen
  install_simple_package cscope
  install_simple_package vim
  install_simple_package wemux
  install_simple_package bc
  install_simple_package sloccount
  install_simple_package cloc
  install_simple_package perltidy
  install_simple_package strace
  install_simple_package yum-utils
  install_simple_package meld
  install_simple_package cpulimit
  install_simple_package npm
  install_simple_package gem
  install_simple_package ruby-devel
  install_simple_package gitstats
  install_simple_package colordiff
  install_simple_package tig
  install_simple_package nmap
  install_simple_package uncrustify
  install_simple_package vagrant
  install_simple_package twin
  install_simple_package iftop
  install_simple_package graphviz
  install_simple_package dsniff
  install_simple_package pyang
  install_simple_package plantuml
  install_simple_package python-matplotlib
  install_simple_package perl-List-AllUtils
  install_simple_package perl-List-UtilsBy
  install_simple_package perl-File-chdir
  install_simple_package perl-Devel-Profiler
  install_simple_package perl-JSON
  install_simple_package xxdiff
  install_simple_package go
  install_simple_package socat
  install_simple_package texlive-glossaries
  install_simple_package youtube-dl
  install_simple_package mplayer
  install_simple_package hwloc
  install_simple_package hwloc-gui
  install_simple_package perl-Text-SpellChecker
  install_simple_package perl-Sysadm-Install
  install_simple_package jhead
  install_simple_package ImageMagick
  install_simple_package perl-Clone
  install_simple_package perl-Storable
  install_simple_package perl-Path-Class
  install_simple_package perl-Image-ExifTool
  install_simple_package perl-DateTime
  install_simple_packege audacity-freeworld
  install_simple_packege sox-plugins-freeworld
  install_simple_packege sox-plugins-nonfree

  sudo rpm -Uf --quiet http://d-rats.com/yum/f11/d-rats-repo-0.1.3-1.fc12.noarch.rpm \
    2>&1 | grep -v "already installed"
  install_simple_package chirp

  sudo debuginfo-install -q glibc \
    | grep -v "already installed and latest version" \
    | grep -v "No debuginfo packages available to install"

  sudo debuginfo-install -q kernel \
    | grep -v "already installed and latest version" \
    | grep -v "No debuginfo packages available to install"

  install_simple_package python3-pyusb
  install_simple_package pyusb

  #install_simple_package luarocks
  #install_simple_package lua-devel
  #sudo luarocks install cw

  npm config set prefix ~/menv/npm
  menv_export PATH=$PATH:$HOME/menv/npm/bin
  npm install --loglevel error -g git-stats &> /dev/null
  npm install --loglevel error -g git-stats-importer &> /dev/null
  npm install --loglevel error -g http-server &> /dev/null

  gem install -q git_stats &> /dev/null
  gem install -q slackcat &> /dev/null
fi

fi
