#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if [ -d ~/.vim ] ; then
  if [ -f ~/.vim/.$menv_gen_tag ] ; then
    $BINRM -rf ~/.vim
  else
    $BINMV --backup=numbered ~/.vim ${menv_backup_dir}/.vim
  fi
fi

mkdir ~/.vim
touch ~/.vim/.$menv_gen_tag

$BINMKDIR -p ~/.vim/plugin

spushd .

cd ~

safe_symlink .vimrc $menv_dotfiles_dir/vimrc

spopd

