#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~

$BINMKDIR -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim \
 https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim

spopd
