#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~

echo "Installing vim pathogen plugin handler."
$MKDIR -p ~/.vim/autoload ~/.vim/bundle
curl -Sso ~/.vim/autoload/pathogen.vim \
 https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

spopd

