#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~/.vim/bundle
github_fetch scrooloose/nerdtree
github_fetch myusuf3/numbers.vim
cd ~/.vim
github_fetch Rip-Rip/clang_complete
$MV clang_complete/bin .
$MV clang_complete/plugin .
$RM -rf clang_complete

github_fetch tpope/vim-fugitive
$MV vim-fugitive/plugin/* plugin/
$RM -rf vim-fugitive

cd ~/.vim/plugin

echo "Installing cscope plugin."
fetch http://cscope.sourceforge.net/cscope_maps.vim

spopd

