#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~
  
safe_symlink .gitconfig $menv_dotfiles_dir/gitconfig
gitVersion=$(git --version | awk -F"version " '{print $2}')
if version_le $gitVersion "1.7.11" ; then
  git config --global push.default upstream
fi

# Let's install these cool ruby scripts for working with git!
#   http://git-wt-commit.rubyforge.org/
wget -O gitwt.tar -q -N --no-check-certificate \
  https://gitorious.org/willgit/mainline/archive-tarball/master
tar -xvf gitwt.tar &> /dev/null

if [ -d willgit-mainline/bin/* ] ; then
  $BINCP  willgit-mainline/bin/* ~/menv/bin
fi

if [ -d willgit-mainline ] ; then
  $BINRM -rf willgit-mainline
fi
$BINRM gitwt.tar

cd $menv_bin_dir

curl -O https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

git clone https://code.google.com/p/gitinspector/

ln -s gitinsepctor/gitinspector/gitinspector.py gitinspector

spopd

