#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~
  
safe_symlink .gitconfig $menv_dotfiles_dir/gitconfig
gitVersion=$(git --version | awk -F"version " '{print $2}')
if version_le $gitVersion "1.7.11" ; then
  git config --global push.default upstream
fi

# Let's install these cool ruby scripts for working with git!
#   http://git-wt-commit.rubyforge.org/
wget -O gitwt.tar -q -N --no-check-certificate \
  https://gitorious.org/willgit/mainline/archive-tarball/master
tar -xvf gitwt.tar &> /dev/null

$CP  willgit-mainline/bin/* ~/menv/bin
$BINRM -rf willgit-mainline
$BINRM gitwt.tar

spopd

