#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

# Only run gnome for gnome <= 3.8.4
gnomeVersion="$(expr "$(gnome-terminal --version)" : '.* \(.*[.].*[.].*\)$')"
if version_ge $gnomeVersion "3.8.4" ; then

spushd .

append_crontab "1 1 * * * ~mokon/menv/bin/rotate_background"

~mokon/menv/bin/rotate_background

avatar=david_bond_social_media.jpg
fetch http://mokonphotography.com/wp-content/uploads/2013/11/$avatar

dbus-send --system --dest=org.freedesktop.Accounts  \
    --type=method_call --print-reply \
    /org/freedesktop/Accounts/User$(id -u) \
    org.freedesktop.Accounts.User.SetIconFile \
    string:"$avatar" &> /dev/null
$RM $avatar

cd ~

FAV_APPS="['gnome-terminal.desktop', 'virt-manager.desktop', 'nautilus.desktop', 'skype.desktop', 'cheese.desktop', 'gedit.desktop', 'google-chrome.desktop', "
function add_app {
  local app="${1}.desktop"
  cp $menv_dotfiles_dir/local/share/applications/${app} .local/share/applications/${app}
  FAV_APPS="$FAV_APPS '${app}',"
}

add_app root-wireshark
add_app gnome-start
gsettings set org.gnome.shell favorite-apps "${FAV_APPS%?}]"

unset add_app

gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.nautilus.preferences always-use-location-entry  true
gsettings set org.gnome.Terminal.Legacy.Settings new-terminal-mode 'tab'
gsettings set org.gnome.gnome-screenshot auto-save-directory file:///home/$USER/pics

PALETTE="['rgb(0,0,0)', 'rgb(205,0,0)', 'rgb(0,205,0)', 'rgb(205,205,0)', 'rgb(30,144,255)', 'rgb(205,0,205)', 'rgb(0,205,205)', 'rgb(229,229,229)', 'rgb(76,76,76)', 'rgb(255,0,0)', 'rgb(0,255,0)', 'rgb(255,255,0)', 'rgb(70,130,180)', 'rgb(255,0,255)', 'rgb(0,255,255)', 'rgb(255,255,255)']"
BG_COLOR="rgb(0,0,0)"
FG_COLOR="rgb(0,255,0)"
BD_COLOR="#9393a1a1a1a1"

p="/org/gnome/terminal/legacy/profiles:/"
profiles=($(dconf list $p | grep ^: | sed 's/\///g'))
for i in ${!profiles[*]} ; do
  if [[ "$(dconf read $p${profiles[i]}/visible-name)" == "'Default'" ]] ; then
    uuid="${profiles[i]}"
  fi
done
p="$p$uuid"
dconf write ${p}palette "[$PALETTE]"

dconf write ${p}bold-color "'$BD_COLOR'"
dconf write ${p}background-color "'$BG_COLOR'"
dconf write ${p}foreground-color "'$FG_COLOR'"

dconf write ${p}use-theme-colors "false"
dconf write ${p}use-theme-background "false"
dconf write ${p}bold-color-same-as-fg "false"

dconf write ${p}scrollback-unlimited "true"

spopd
else
  echo "Unsupported Gnome Version [$gnomeVersion] detected."
fi

