#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

spushd .

if [ $MENV_DESKTOP -ne 0 ] ; then
  if grep -q "* soft nofile 4096" /etc/security/limits.conf &> /dev/null ; then
    echo "menv note, high file limit already installed"
  else
    echo "* soft nofile 4096" | sudo tee -a /etc/security/limits.conf &> /dev/null
    echo "* hard nofile 4096" | sudo tee -a /etc/security/limits.conf &> /dev/null
  fi
fi

spopd
