#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if [ $MENV_DESKTOP -ne 0 ] ; then

spushd .

if [ -f /etc/selinux/config ] ; then
  cp /etc/selinux/config $menv_sysbackup_dir
fi

sudo setenforce 0 &> /dev/null

cat <<HEREDOC | sudo tee /etc/selinux/config &> /dev/null
SELINUX=disabled
SELINUXTYPE=targeted
HEREDOC

spopd

fi
