#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~

if [ -d ~/.ssh ] ; then
  if [ -f ~/.ssh/.$menv_gen_tag ] ; then
    $RM -rf ~/.ssh/config
  else
    $MV --backup=numbered ~/.ssh/config ${menv_backup_dir}/.ssh/config
  fi
else
  mkdir ~/.ssh
fi

touch ~/.ssh/.$menv_gen_tag

safe_symlink ~/.ssh/config $menv_dotfiles_dir/ssh/config

if [ ! -f ~/.ssh/id_rsa.pub ]; then
  ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa
fi

spopd

