#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~

if [ -d ~/.ssh ] ; then
  if [ -f ~/.ssh/.$menv_gen_tag ] ; then
    $BINRM -rf ~/.ssh/config
  else
    $BINMV --backup=numbered ~/.ssh/config ${menv_backup_dir}/.ssh/config
  fi
else
  mkdir ~/.ssh
fi

touch ~/.ssh/.$menv_gen_tag

safe_symlink ~/.ssh/config $menv_dotfiles_dir/ssh/config

chmod 600 ~/.ssh/config

if [ ! -f ~/.ssh/id_rsa.pub ]; then
  ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa
fi

if [ $MENV_ROOT_ACCESS -ne 0 ] ; then
  read -t 5 -p "Do you want to enable sshd? " -n 1 -r
  echo

  if [[ $REPLY =~ ^[Yy]$ ]] ; then
    sudo /sbin/chkconfig sshd on
   
    if ! grep -q "UseDNS no" /etc/ssh/sshd_config &> /dev/null ; then 
      echo "UseDNS no" | sudo tee -a /etc/ssh/sshd_config
    fi
  fi
fi

spopd

