#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

if [ -d $vim_dir ] ; then
  if [ -f $vim_dir/.$menv_gen_tag ] ; then
    $RM -rf $vim_dir
  else
    $MV --backup=numbered $vim_dir ${menv_backup_dir}/${vim_dir}
  fi
fi

mkdir $vim_dir
touch $vim_dir/.$menv_gen_tag

pushd .

cd ~

safe_symlink $vimrc $menv_dotfiles_dir/menv_$vimrc

popd

