#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

pushd .

cd ~

echo "Installing vim pathogen plugin handler."
$MKDIR -p $vim_dir/autoload $vim_dir/bundle
curl -Sso $vim_dir/autoload/pathogen.vim \
 $raw_gh_url/tpope/vim-pathogen/master/autoload/pathogen.vim

cd $vim_dir/bundle
github_fetch scrooloose/nerdtree
github_fetch myusuf3/numbers.vim

cd $vim_dir
github_fetch Rip-Rip/clang_complete
$CP -R clang_complete/* .
$RM -rf clang_complete
# TODO cleanup some of the example etc this installs.

$MKDIR -p $vim_dir/plugin
cd $vim_dir/plugin

echo "Installing cscope plugin."
fetch http://cscope.sourceforge.net/cscope_maps.vim

popd

