#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved
# requirements gnome <= 3.8.4, desktop != 0

cd ~

function rm_app {
  local app="${1}.desktop"
  if [ -f .local/share/applications/${app} ] ; then
    $BINRM .local/share/applications/${app}
  fi
}

if [ -f ~/.local/share/recently-used.xbel ] ; then
  sudo chattr -i ~/.local/share/recently-used.xbel
  sudo $BINRM ~/.local/share/recently-used.xbel
fi

delete_crontab rotate_background
delete_crontab mute_volume

rm_app gnome-start
gsettings set org.gnome.shell favorite-apps "['gnome-terminal.desktop']"

unset rm_app

if_symlink_rm ~/.config/gtk-3.0/settings.ini
