#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

export menv_dir=~/menv
export menv_backup_dir=$menv_dir/backup
export menv_trash_dir=$menv_dir/trash
export menv_cache_dir=$menv_dir/cache
export menv_downloads_dir=$menv_cache_dir/downloads
export menv_sysbackup_dir=$menv_cache_dir/sysbackup
export menv_screenshots_dir=$menv_cache_dir/screenshots
export menv_logs_dir=$menv_cache_dir/logs
export menv_history_dir=$menv_cache_dir/history
export menv_bin_dir=$menv_dir/bin
export menv_core_dir=$menv_dir/core
export menv_local_dir=$menv_dir/local
export menv_local_bin_dir=$menv_local_dir/bin
export menv_local_save_dir=$menv_local_dir/save
export menv_cache_bin_dir=$menv_cache_dir/bin
export menv_cache_npm_dir=$menv_cache_dir/npm
export menv_cache_npm_bin_dir=$menv_cache_npm_dir/bin
export menv_cache_go_dir=$menv_cache_dir/go
export menv_cache_go_bin_dir=$menv_cache_go_dir/bin
export menv_cache_dotfiles_dir=$menv_cache_dir/dotfiles
export menv_cache_vimrc_style_dir=$menv_cache_dotfiles_dir/vimrc_style
export menv_dotfiles_dir=$menv_dir/dotfiles
export menv_vimrc_style_dir=$menv_dotfiles_dir/vimrc_style
export menv_targets_dir=${menv_dir}/targets
export menv_pkgs_dir=${menv_dir}/pkgs
export menv_install_opts_file=$menv_cache_dir/install_opts
export menv_last_no_update_file=$menv_cache_dir/last_no_update
export menv_pkg_install_log=$menv_cache_dir/pkgs_install.log
export menv_source_log=$menv_cache_dir/sourced_children_target.log
