#!/bin/bash
# (C) 2013-2016 David 'Mokon' Bond, All Rights Reserved

# A function to determine the distribution and pkg management tool
menv_function determine_dist
function determine_dist {
  if type lsb_release &> /dev/null ; then
    DIST=$(lsb_release -a | grep "Distributor ID" | awk {'print tolower($3)'})
  else
    DIST=""
  fi

  if [ -z $DIST ] && [ -f /etc/redhat-release ] ; then
    if grep -q Fedora /etc/redhat-release; then
      DIST=fedora
    fi

    if grep -q CentOS /etc/redhat-release; then
      DIST=centos
    fi
  fi

  if [ -z $DIST ] && [ -f /etc/debian_version ] ; then
    DIST=debian
  fi

  if [ -z $DIST ] && [ -f /etc/os-release ] ; then
    DIST="unknown"
  fi

  case $DIST in
    *fedora*|*centos*)
      PKG_TYPE=rpm ;
      version=`sed -rn 's/VERSION_ID=(.*)/\1/p' /etc/os-release | sed 's/"//g'`

      if [ "$version" -ge "22" ] ; then
        PKG_MGMT=dnf
      else
        PKG_MGMT=yum
      fi
      ;;
    *redhat*) PKG_TYPE=rpm ; PKG_MGMT=yum ;;
    *debian*|*ubuntu*) PKG_TYPE=dpkg ; PKG_MGMT=apt ;;
    *) PKG_TYPE=unknown ; PKG_MGMT=unknown ; echo "Unknown Distribution" ;;
  esac

  menv_export DIST
  menv_export PKG_TYPE
  menv_export PKG_MGMT
}

determine_dist

menv_alias dist_install=${DIST}_install
menv_alias dist_local_install=${DIST}_local_install
menv_alias ins=dist_install
menv_alias ${DIST}_install=${PKG_MGMT}_install
menv_alias ${DIST}_local_install=${PKG_MGMT}_local_install

menv_alias dist_update=${DIST}_update
menv_alias ${DIST}_update=${PKG_MGMT}_update

menv_alias yum_install="sudo yum install -q -y"
menv_alias dnf_install="sudo dnf install -q -y"
menv_alias apt_install="sudo apt-get --yes --force-yes install -qq"

menv_alias yum_update="sudo yum update -q -y"
menv_alias dnf_update="sudo dnf update -q -y"

menv_alias yum_local_install="sudo yum localinstall -q -y --nogpgcheck"
menv_alias dnf_local_install="sudo dnf install -q -y"

menv_alias global_install_package="install_package"

menv_alias update_packages=dist_update

menv_function install_package
function install_package {
  dist_to_pkg=$1

  eval "local pkg=\${$dist_to_pkg[$DIST]}"

  if [ "$pkg" == "skip" ]; then
    return 0
  fi

  echo "Installing package '$pkg'"

  dist_install $pkg 2>&1 | \
    tee -a ${menv_pkg_install_log} | \
    grep -v "already installed"
}

menv_function local_install_package
function local_install_package {
  pkg=$1

  dist_local_install $pkg 2>&1 | \
    tee -a ${menv_pkg_install_log} | \
    grep -v "already installed\|kB/s"
}

menv_function install_simple_package
function install_simple_package {
  local pkg_name=$1

  declare -A pkg_arr
  pkg_arr=(
    [fedora]="$pkg_name"
    [centos]="$pkg_name"
    [debian]="$pkg_name"
    [ubuntu]="$pkg_name"
  )

  install_package pkg_arr
}

menv_function install_simple_packages
function install_simple_packages {
  for package in "$@" ; do
    install_simple_package $package
  done
}

menv_function npm_install_package
function npm_install_package {
  local pkg=$1
  echo "Installing npm package '$pkg'"
  npm install --loglevel error -g $pkg 2>&1 | \
    tee -a ${menv_pkg_install_log} > /dev/null
}

menv_function npm_install_packages
function npm_install_packages {
  for package in "$@" ; do
    npm_install_package $package
  done
}

menv_function gem_install_package
function gem_install_package {
  local pkg=$1

  echo "Installing gem package '$pkg'"
  gem install -q --install-dir=${menv_cache_bin_dir} -n ${menv_cache_bin_dir} $pkg 2>&1 | \
    tee -a ${menv_pkg_install_log} > /dev/null
}

menv_function gem_install_packages
function gem_install_packages {
  for package in "$@" ; do
    gem_install_package $package
  done
}

menv_function pip_install_package
function pip_install_package {
  local pkg=$1

  echo "Installing pip package '$pkg'"
  pip -q install $pkg 2>&1 | \
    tee -a ${menv_pkg_install_log} > /dev/null
}

menv_function pip_install_packages
function pip_install_packages {
  for package in "$@" ; do
    pip_install_package $package
  done
}

menv_function create_yum_dnf_repo
function create_yum_dnf_repo {
  repo=$1
  url=$2
  key=$3

  if [ -z ${key+x} ]; then
    key="\ngpgcheck=0"
  elif [ "$key" == "norepo" ]; then
    key="\ngpgcheck=0\nrepo_gpgcheck=0"
  else
    key="\ngpgcheck=1\ngpgkey=${key}"
  fi


  cat << EOF | sudo tee /etc/yum.repos.d/${repo}.repo &> /dev/null
[${repo}]
name=${repo}
baseurl=${url}/\$basearch
enabled=1${key}
EOF
}

menv_function parse_and_install_pkgs_file
function parse_and_install_pkgs_file {
  local pkg=$1

  while read -r fedora_pkg debian_pkg ubuntu_pkg centos_pkg; do
    if [ -z "$debian_pkg" ] ; then
      debian_pkg=$fedora_pkg
    fi

    if [ -z "$ubuntu_pkg" ] ; then
      ubuntu_pkg=$debian_pkg
    fi

    if [ -z "$centos_pkg" ] ; then
      centos_pkg=$fedora_pkg
    fi

    declare -A pkg_arr
    pkg_arr=(
      [fedora]="$fedora_pkg"
      [centos]="$centos_pkg"
      [debian]="$debian_pkg"
      [ubuntu]="$ubuntu_pkg"
    )

    install_package pkg_arr

  done < ${menv_pkgs_dir}/${pkg}.pkgs
}
