#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved
BINRM="/bin/rm -R"
$BINRM ~/.gntrc
$BINRM ~/.gitconfig
$BINRM ~/.config/user-dirs.conf
$BINRM ~/.tmux.conf
$BINRM ~/menv
$BINRM ~/.bashrc
$BINRM ~/.vimrc
$BINRM ~/.vim
$BINRM ~/.bash_profile
$BINRM ~/.bash_logout
