#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

if [[ "$SHELL" != *bash* ]] ; then
  echo "menv requires a bash shell, bye"
  exit -1
fi

# A global array of functions used to unset funcs on cleanup.
menv_funcs=()

# A function which pushes a function onto the menv array of functions.
function menv_function {
  menv_funcs+=($1)
}
menv_function menv_function

# A global array of aliases used to unalias aliases on cleanup.
menv_aliases=()

# A function which pushes an alias onto the menv array of aliases.
menv_function menv_alias
function menv_alias {
  alias "$*"
  menv_aliases+=($1)
}

# A global array of exports used to unset exports on cleanup.
menv_exports=()

# A function which pushes an export onto the menv array of exports.
menv_function menv_export
function menv_export {
  export "$*"
  menv_exports+=($1)
}

menv_export menv_dir=~/menv

menv_export menv_backup_dir=$menv_dir/backup
menv_export menv_trash_dir=$menv_dir/trash
menv_export menv_cache_dir=$menv_dir/cache

menv_export menv_gen_tag="menv_generated"

menv_export vim_dir=~/.vim
menv_export menv_lib_dir=lib
menv_export menv_targets_dir=${menv_dir}/targets

# Absolute paths for lsb commands.
menv_export MV=/bin/mv
menv_export LN=/bin/ln
menv_export RM=/bin/rm
menv_export CP=/bin/cp
menv_export TAR=/bin/tar
menv_export MKDIR=/bin/mkdir

menv_export raw_gh_url="https://raw.github.com"
menv_export menv_git_url="https://github.com/Mokon/menv.git"
menv_export menv_url="${raw_gh_url}/Mokon/menv"
menv_export menv_master_url="${menv_url}/master"
menv_export menv_dotfiles_url="${menv_master_url}/dotfiles"

menv_export menv_local_dir=$menv_dir/local
menv_export menv_dotfiles_dir=$menv_dir/dotfiles
menv_export menv_local_login=$menv_local_dir/login
menv_export menv_local_nonlogin=$menv_local_dir/nonlogin
menv_export menv_target_handler=$menv_dir/core/target_handler

menv_export bashrc=.bashrc
menv_export bash_profile=.bash_profile
menv_export vimrc=.vimrc
menv_export tmux_conf=.tmux.conf
  
################################################################################

# executes a target
menv_function menv_target
function menv_target {
  local file=$1
  
  source $menv_targets_dir/$file
  echo hi
  if [ $(ls $menv_targets_dir/${file}.d ) ] ; then
  echo bye1
    source $menv_targets_dir/${file}.d/* # TODO Have a module exclude pattern matcher
  fi
  echo bye2
}

# Aux function to wget a file. If the second param is set then this is the name
# of the produced file.
menv_function fetch
function fetch {
  local url=$1

  command -v wget >/dev/null 2>&1 || { echo >&2 "wget not found" ; return ; }
  if [ -n "$2" ] ; then
    local fname=$2
  else
    local fname=`basename ${url}`
  fi
  wget -O $fname -q -N --no-check-certificate ${url}
}

# An aux function to grab a git repo
menv_function menv_github_fetch
function menv_github_fetch {
  local repo=$1

  fetch https://github.com/$repo/archive/master.tar.gz
    
  tar -xzf master.tar.gz
  $RM -f master.tar.gz
  $MV "$(basename $repo)-master" $(basename $repo)
}

