#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

pushd . &> /dev/null

cd ~

file="~/master.tar.gz"
    
/bin/tar -xzf $file
/bin/rm -f $file
/bin/mv menv-master menv

find menv/ -not -path "menv/vault/*/*" -and -not -path "menv/backup/*/*" -and -name .gitkeep -exec rm -rf {} \;

source ~/menv/core/target_handler

source ~/.bash_profile

popd &> /dev/null
