#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function motd {
# Terminal colors, assuming 256 colors.
local TC_RESET="[0m"
local TC_SKY="[0;37;44m"
local TC_GRD="[0;30;42m"
local TC_TEXT="[38;5;203m"
local CLREOL=$'\x1B[K'
local tmp=`mktemp`
echo -n "${TC_SKY}
              ( \`   )_
             (    )    \`)
           (_   (_ .  _) _)
                                          _
                                         (  )
          _ .                         ( \`  ) . )
        (  _ )_                      (_, _(  ,_)_)
      (_  _(_ ,)

${TC_TEXT}[44m                ##     ##  #######  ##    ##  #######  ##    ##
                ###   ### ##     ## ##   ##  ##     ## ###   ##
                #### #### ##     ## ##  ##   ##     ## ####  ##
                ## ### ## ##     ## #####    ##     ## ## ## ##
                ##     ## ##     ## ##  ##   ##     ## ##  ####
                ##     ## ##     ## ##   ##  ##     ## ##   ###
                ##     ##  #######  ##    ##  #######  ##    ##
${TC_SKY}
               _  _
              ( \`   )_
             (    )    \`)
           (_   (_ .  _) _)
                                                        (  )
                      _, _ .                         ( \`  ) . )
                     ( (  _ )_                      (_, _(  ,_)_)
                   (_(_  _(_ ,)

${TC_GRD}" >> $tmp

echo -e "\n                           Welcome to Mokon's Computer!\n" >> $tmp

echo -n "${TC_GRD}" >> $tmp
nodeinfo >> $tmp
echo ${TC_RESET} >> $tmp

sed ":a;N;\$!ba;s/\\n/${CLREOL}\\n/g" $tmp
}

if [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; then
  motd | sed -e :a -e 's/^.\{1,78\}$/& /;ta'
else
  motd
fi
