#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

motd=$(
# Terminal colors, assuming 256 colors.
TC_RESET="[0m"
TC_SKY="[0;37;44m"
TC_GRD="[0;30;42m"
TC_TEXT="[38;5;203m"
CLREOL=$'\x1B[K'
tmp=`mktemp`
echo -n "${TC_SKY}
              ( \`   )_
             (    )    \`)
           (_   (_ .  _) _)
                                          _
                                         (  )
          _ .                         ( \`  ) . )
        (  _ )_                      (_, _(  ,_)_)
      (_  _(_ ,)

${TC_TEXT}[44m                ##     ##  #######  ##    ##  #######  ##    ##
                ###   ### ##     ## ##   ##  ##     ## ###   ##
                #### #### ##     ## ##  ##   ##     ## ####  ##
                ## ### ## ##     ## #####    ##     ## ## ## ##
                ##     ## ##     ## ##  ##   ##     ## ##  ####
                ##     ## ##     ## ##   ##  ##     ## ##   ###
                ##     ##  #######  ##    ##  #######  ##    ##
${TC_SKY}
               _  _
              ( \`   )_
             (    )    \`)
           (_   (_ .  _) _)
                                                        (  )
                      _, _ .                         ( \`  ) . )
                     ( (  _ )_                      (_, _(  ,_)_)
                   (_(_  _(_ ,)

${TC_GRD}" >> $tmp

echo -e "\n                           Welcome to Mokon's Linux!\n" >> $tmp

echo -n "${TC_GRD}" >> $tmp
nodeinfo >> $tmp
echo ${TC_RESET} >> $tmp

sed ":a;N;\$!ba;s/\\n/${CLREOL}\\n/g" $tmp

unset TC_RESET
unset TC_SKY
unset TC_GRD
unset TC_TEXT
)

if [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; then
  echo $motd | sed -e :a -e 's/^.\{1,78\}$/& /;ta' 
else
  echo $motd
fi

