#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

menv_function empty_ru
function empty_ru {
  if [ -f ~/.local/share/recently-used.xbel ] ; then
    sudo chattr -i ~/.local/share/recently-used.xbel
  fi
  echo "" | sudo tee ~/.local/share/recently-used.xbel > /dev/null
  sudo chattr +i ~/.local/share/recently-used.xbel
}

menv_alias sudo='sudo ' # Allow sudo to be used on aliases.
menv_alias rm="$BINMV --target-directory ${menv_trash_dir}" # Safe delete
menv_alias delete_immediately="$BINRM -rf"
menv_alias di="$BINRM -rf"
menv_alias empty_logs="$BINRM -rf ${menv_logs_dir}/*"
menv_alias empty_thumbs="$BINRM -rf ~/.cache/thumbnails/"
menv_alias empty_trash="$BINRM -rf ${menv_trash_dir}/*"
menv_alias empty_dl="$BINRM -rf ${menv_downloads_dir}/*"
menv_alias empty_all="empty_trash; empty_dl; ${DIST}_empty_trash; empty_logs; empty_ru; empty_thumbs"
menv_alias empty_skype="$BINRM -rf ~/.Skype"
menv_alias system_clean="empty_all ; empty_skype"
menv_alias bim="vim"
menv_alias e="exit"
menv_alias ex="exit"
menv_alias exi="exit"
menv_alias ls="ls --color"
menv_alias bx="source ~/$bashrc"
menv_alias mv="$BINMV -i --backup=numbered"
menv_alias cp="$BINCP --backup=numbered"
menv_alias rm_all_swap="$BINRM *.swp"
menv_alias fkill="sudo kill -9"
menv_alias less="less -R"
menv_alias grep="grep --color=always --exclude=\"*cscope*\" --exclude-dir=\".pc\""
menv_alias what_time_is_it="date +%I:%M"
menv_alias size="du -sh "
menv_alias psa="ps -aux -ww"
menv_alias hosts="cat /etc/hosts"
menv_alias edit_dns="sudo vim /etc/resolv.conf"
menv_alias process_tree="ps -e -o pid,args --forest -ww"
menv_alias httpp="python -m SimpleHTTPServer"
menv_alias "?"="ls"
menv_alias gg="poweroff"
menv_alias re="reboot"
menv_alias find_duplicate_files="fdupes -r"
menv_alias plz="sudo"
menv_alias nonkernel_processes="ps --ppid 2 --deselect u -ww"
menv_alias pslist="ps --ppid 2 --deselect u --forest -ww"
menv_alias nonkernel_top="top -U \!2"
menv_alias watch="watch "
menv_alias vum="vim"
menv_alias vun="vim"
menv_alias show_common_files="ls -R ~/ ~/menv/local --hide='*menv*' --hide='*git*'"
menv_alias limit_program_one_percent_cpu="cpulimit -l 1 -i"
menv_alias merge="rsync -a" # from to
menv_alias sudo_preserve_env="sudo -E sh -c"
menv_alias show_current_cgroup="ps h -p $PPID -o cgroup | sed 's/.*\///g'"
menv_alias scp="rsync -avzP"
menv_alias scpthrough="scp -3"
menv_alias show_bus_info="sudo lshw -c network -businfo"
menv_alias view_image_metadata="exiftool"
menv_alias view_image_metadata2="jhead"
menv_alias remove_image_metadata="mogrify -strip"
menv_alias set_backlight="backlight -set"
menv_alias display_serial_number="sudo dmidecode -s system-serial-number"
menv_alias timestamp_to_date="date -d"
menv_alias human_readable="numfmt --to=iec-i --suffix=B --padding=7"
menv_alias get_screen_resolutions="xrandr"
menv_alias load_desktop="conky -c ~/menv/desktop/desktop"
menv_alias tile_images="montage *.JPG -tile 2x2 -geometry +0+0 result.jpg"
