#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

alias logs_since_boot="journalctl --boot"
alias count_files_in_directory_r="find . -type f | wc -l"
alias sudo='sudo ' # Allow sudo to be used on aliases.
if [ $DIST != "darwin" ] ; then
  alias rm="$BINMV --target-directory ${menv_trash_dir}" # Safe delete
else
  function rm {
    $BINMV $@ ${menv_trash_dir}
  }
fi
alias delete_immediately="$BINRM -rf"
alias di="$BINRM -rf"
alias empty_logs="$BINRM -rf ${menv_logs_dir}/*"
alias empty_thumbs="$BINRM -rf ~/.cache/thumbnails/"
alias empty_trash="$BINRM -rf ${menv_trash_dir}/*"
alias empty_dl="$BINRM -rf ${menv_downloads_dir}/*"
alias empty_all="empty_trash; empty_dl; ${DIST}_empty_trash; empty_logs; empty_ru; empty_thumbs"
alias empty_skype="$BINRM -rf ~/.Skype"
alias system_clean="empty_all ; empty_skype"
alias bim="vim"
alias e="exit"
alias ex="exit"
alias exi="exit"
alias xit="exit"
if [ $DIST != "darwin" ] ; then
  alias ls="ls --color"
else
  alias ls="ls -G"
fi
alias bx="source ~/$bashrc"
alias mv="$BINMV_BCK -i"
alias cp="$BINCP_BCK"
alias rm_all_swap="$BINRM *.swp"
alias fkill="sudo kill -9"
alias less="less -R"
alias grep="grep --color=always --exclude=\"*cscope*\" --exclude-dir=\".pc\" --devices=skip"
alias what_time_is_it="date +%I:%M"
alias size="du -sh "
alias psa="ps -aux -ww"
alias hosts="cat /etc/hosts"
alias edit_dns="sudo vim /etc/resolv.conf"
alias process_tree="ps -e -o pid,args --forest -ww"
alias httpp="python -m SimpleHTTPServer"
alias "?"="ls"
alias gg="poweroff"
alias re="reboot"
alias find_duplicate_files="fdupes -r"
alias plz="sudo"
alias nonkernel_processes="ps --ppid 2 --deselect u -ww"
alias pslist="ps --ppid 2 --deselect u --forest -ww"
alias nonkernel_top="top -U \!2"
alias watch="watch "
alias vum="vim"
alias vun="vim"
alias show_common_files="ls -R ~/ ~/menv/vault --hide='*menv*' --hide='*git*'"
alias limit_program_one_percent_cpu="cpulimit -l 1 -i"
alias merge="rsync -a" # from to
alias sudo_preserve_env="sudo -E sh -c"
alias show_current_cgroup="ps h -p $PPID -o cgroup | sed 's/.*\///g'"
alias scp="rsync -avzP"
alias scpthrough="scp -3"
alias show_bus_info="sudo lshw -c network -businfo"
alias view_image_metadata="exiftool"
alias view_image_metadata2="jhead"
alias remove_image_metadata="mogrify -strip"
alias set_backlight="backlight -set"
alias display_serial_number="sudo dmidecode -s system-serial-number"
alias timestamp_to_date="date -d"
alias human_readable="numfmt --to=iec-i --suffix=B --padding=7"
alias get_screen_resolutions="xrandr"
alias load_desktop="conky -c ~/menv/desktop/desktop"
alias tile_images="montage *.JPG -tile 2x2 -geometry +0+0 result.jpg"
alias print_image_metadata="identify -verbose "
alias directory_diff="diff -bur"
alias delete_newline_at_end_of_file="perl -pi -e 'chomp if eof' "
