#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

menv_function extract
function extract {
  local file=$1
  
  case $file in
    *.tar.gz) tar -xzvf $file ;;
    *.tar) tar -xvf $file ;;
    *.zip) unzip $file ;;
    *.rar) unrar $file ;;
    *) echo "I don't know how to extract that file extension."
  esac
}

menv_alias tarball="tar cvzf" # Create

