#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function extract {
  local file=$1

  case $file in
    *.tgz) tar zxvf $file ;;
    *.tar.xz) tar xf $file ;;
    *.tar.gz) tar -xzvf $file ;;
    *.tar) tar -xvf $file ;;
    *.zip) unzip $file ;;
    *.rar) unrar $file ;;
    *) echo "I don't know how to extract that file extension."
  esac
}

function compress {
  local file=${1%/}
  local archive_type=${2:-tar}

  case $archive_type in
    tar) tar cvzf ${file}.tar $file ;;
    zip) zip -r ${file}.zip $file ;;
    rar|*) echo "I don't know how to compress that archive type."
  esac
}
