#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function hash_dir {
  local dir=$1
  tar -cf - $dir | md5sum
}

function backup {
  local backup_location=${1:-/backup}

  local date=`date +"%m_%d_%Y"`
  local hostname=`hostname`
  local backup_dir=$backup_location/${date}_${hostname}/

  start=$(date)

  spushd .
  echo "Starting Backup"

  mkdir $backup_dir
  cd $backup_dir

  mkdir git
  cd git
  mclone
  cd ..

  # Add --info=progress2 once rsync in distos is 3.1.0
  rsync -ar ~/menv/vault .

  vault_hash=$(hash_dir vault)
  git_hash=$(hash_dir git)

  cp ~/.config/google-chrome/Default/Bookmarks .
  cp /etc/hosts .

  end=$(date)

  cat << EOF > metadata
start time = ${start}
end time = ${end}
local dir hash = ${vault_hash}
git dir hash = ${git_hash}
EOF

  echo "Backup Completed"
  spopd
}

function restore_backup {
  local date=${1:-`date +"%m_%d_%Y"`}
  local backup_location=${2:-/backup}
  local hostname=${3:-`hostname`}

  local backup_dir=$backup_location/${date}_${hostname}/

  spushd .
  echo "Starting Resoration of Backup"

  rsync -ar $backup_dir ~/menv/vault

  chown -R $USER ~/menv/vault
  chgrp -R $USER ~/menv/vault

  echo "Restoration of Backup Complete"
  spopd
}

function mclone {
  echo -n Password:
  read -s password
  echo

  for repo in `github_repos $GITHUB_TOKEN`; do
    git clone https://Mokon:$password@github.com/${repo}.git
  done
}

function mk_private {
  dir=$1

  sudo chown -R root $dir
  sudo chgrp -R root $dir
  sudo chmod -R 700 $dir
  sudo mv $dir ~mokon/.private
}

alias shred="echo 'Are you sure you meant to shred? Call shred explicitly.'"
alias scrub="echo 'Are you sure you meant to scrub? Call scrub explicitly.'"

function wipe_and_format_drive {
  local device=$1
  local drive_id=`printf "%03d" $2`
  local drive_type=${3:-SATA}
  local os=${4:-linux}

  if [ -z ${device+unset} ]; then
    echo "Please pass a device"
    return
  fi

  if [ ! -b "/dev/${device}" ] ;  then
    echo "/dev/${device} is not a block device!"
  fi

  echo "Device to be Whiped Summary"
  echo "-------------------------------------------------"
  df -h |grep $device
  sudo blkid |grep $device
  sudo lsblk |grep $device
  echo "-------------------------------------------------"

  read -t 5 -p

  cat << EOF
You are about to format a device. I have just printed a summary about the
device. Please confirm this is in fact the device you want to wipe. After this
process is done no data will be recoverable from this device."
EOF
  read -p "Wipe device? [y/n]" -n 1 -r

  if [[ $REPLY =~ ^[Yy]$ ]] ; then
    sudo /usr/bin/shred -v /dev/${device}
    sudo /usr/bin/scrub -p bsi /dev/${device}

    sudo fdisk /dev/${device} << END
o
n
p
1


w
END

    partprobe
    umount /dev/${device}1 &> /dev/null

    case $os in
      linux)
        sudo mkfs.ext4 -L "Mokon_${drive_type}_${drive_id}" /dev/${device}1
        ;;
      windows)
        sudo mkfs.ntfs -L "Mokon_${drive_type}_${drive_id}" /dev/${device}1
        ;;
    esac
  fi
}
