#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

menv_function backup
function backup {
  local backup_location=${1:-/backup}

  local date=`date +"%m_%d_%Y"`
  local hostname=`hostname`
  local backup_dir=$backup_location/${date}_${hostname}/

  spushd .
  echo "Starting Backup"

  mkdir $backup_dir
  cd $backup_dir

  # Add --info=progress2 once rsync in distos is 3.1.0
  rsync -ar ~/menv/local .

  mkdir git
  cd git
  mclone
  cd ..

  cp ~/.config/google-chrome/Default/Bookmarks .

  echo "Backup Completed"
  spopd
}

menv_function restore_backup
function restore_backup {
  local date=${1:-`date +"%m_%d_%Y"`}
  local backup_location=${2:-/backup}

  local hostname=`hostname`
  local backup_dir=$backup_location/${date}_${hostname}/

  spushd .
  echo "Starting Resoration of Backup"

  mkdir $backup_dir
  rsync -ar $backup_dir ~/menv/local

  echo "Restoration of Backup Complete"
  spopd
}

menv_function mclone
function mclone {
  # public
  git clone https://Mokon@github.com/Mokon/menv.git
  git clone https://Mokon@github.com/Mokon/mfit.git
  git clone https://Mokon@github.com/Mokon/genealogy.git
  git clone https://Mokon@github.com/Mokon/mcommon.git
  git clone https://Mokon@github.com/Mokon/mspe.git
  git clone https://Mokon@github.com/Mokon/mai.git
  git clone https://Mokon@github.com/Mokon/scrabble.git
  git clone https://Mokon@github.com/Mokon/mfin.git

  # private
  git clone https://Mokon@github.com/Mokon/qubiquid.git
  git clone https://Mokon@github.com/Mokon/cc.git
  git clone https://Mokon@github.com/Mokon/code.git
}

menv_function mk_private
function mk_private {
  dir=$1

  sudo chown -R root $dir
  sudo chgrp -R root $dir
  sudo chmod -R 700 $dir
  sudo mv $dir ~mokon/.private
}

