#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

alias ni="nodeinfo"
alias list_block_devices="lsblk"
alias hdinfo="lsscsi ; lsblk ; df -h"

function cp_cd {
  dd if=/dev/cdrom of=~/"$(cd-info |grep Volume |grep -v Set|awk '{print $3}').iso" bs=2048 conv=sync,notrunc && sync
}

alias goto_usb="/run/media/`whoami`/"

function flash_image {
  image_file=$1
  dev=${2:-/dev/sdb}

  sudo dd if=$image_file of=$dev bs=1M && sync
}
