#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

menv_alias ni="nodeinfo"
menv_alias list_block_devices="lsblk"
menv_alias hdinfo="lsscsi ; lsblk ; df -h"

menv_function cp_cd
function cp_cd {
  dd if=/dev/cdrom of=~/"$(cd-info |grep Volume |grep -v Set|awk '{print $3}').iso" bs=2048 conv=sync,notrunc
}

menv_alias goto_usb="/run/media/`whoami`/"

