#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

export HISTCONTROL=ignoredups:erasedups
export HISTFILE=${menv_history_dir}/bash_history.${BASHPID}
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'} history -a; history -c; history -r"

shopt -s histappend

export HISTTIMEFORMAT='%F %T '
export HISTIGNORE="reset:clear:exit:shutdown*:reboot:*systemctl poweroff*:*systemctl reboot*"
export HISTSIZE=10000
export HISTFILESIZE=10000
alias search_history="history | grep "
alias sh=search_history
alias chistory="history | cut -c 8-"

function cd {
  local default_dir=~
  if dir=`realpath "${1:-$default_dir}"` ; then
    dirstack=("${dirstack[@]}" $(pwd))
    builtin cd "$dir"
  fi

  pushd . &> /dev/null

  while [ `pwd` != "/" ] ; do
    if [ -f cscope.out ] ; then
      export CSCOPE_DB=`realpath cscope.out`
      break
    fi
    builtin cd ..
  done

  popd &> /dev/null
}

function mpop {
  builtin cd ${dirstack[@]:(-1)}
  dirstack=(${dirstack[@]:0:$((${#dirstack[@]}-1))})
}

function mdirs {
  echo ${dirstack[@]}
}
