#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function ni_line {
    local line=$1
    echo $line | cut -c 1-79
}

function nodeinfo {
  local TC_RED="[0;31;42m"
  local TC_RESET="[0m"
  if [ $DIST != "darwin" ] ; then
    local MEMT=`cat /proc/meminfo | grep MemTotal`
    local SWAT=`cat /proc/meminfo | grep '^SwapTotal:'`
    local PMODEL=`cat /proc/cpuinfo | \
      grep '^model name' | awk '{print $4 $5 $6}' | head -1`
    local PMHZ=`cat /proc/cpuinfo | \
      grep '^cpu MHz' | awk '{print $4}'| sed -e 's/\.[0-9]*//g' | head -1`
    local PVENDOR=`cat /proc/cpuinfo | \
      grep '^vendor_id' | awk '{print $3}' | head -1`
    local PNUMS=`cat /proc/cpuinfo | \
      grep '^processor' | wc -l | awk '{print $1}' | head -1`
    if ! test -x "$(command -v "sensors")" ; then
      local CPUTMP=`sensors 2> /dev/null|grep CPU: | sed 's/^.*: *//'`
    fi
  fi

  if [ $DIST != "darwin" ] ; then
    os=`uname -o`
  else
    os="Mac OSX"
  fi
  ni_line "OS............: ${os/GNU\//}"
  ni_line "Distribution..: $DIST"
  ni_line "Pkt Mgmt......: $PKG_MGMT"
  ni_line "Hostname......: `uname -n`"
  if [ $DIST != "darwin" ] ; then
    ni_line "Address(es)...: `/sbin/ip address | grep "inet" \
                             | grep -v '127.\|::1\|fe80::' | awk '{print $2}' \
                             | sed ':a;N;$!ba;s/\n/\n..............: /g'` "
  fi
  ni_line "Kernel........: `uname -s ` `uname -r`"
  ni_line "Machine HW....: `uname -m`"
  if uptime -p &> /dev/null ; then
    ni_line "Uptime........: `uptime -p | sed 's/.*up ([^,]*), .*/1/'i`"
  else
    ni_line "Uptime........: `uptime | sed 's/.*up ([^,]*), .*/1/'`"
  fi
  if [ $DIST != "darwin" ] ; then
    ni_line "Memory........: `echo $MEMT | awk {'print $2'}` `echo $MEMT \
                                      | awk {'print $3'}`"
    ni_line "SWAP..........: `echo $SWAT | awk {'print $2'}` `echo $SWAT \
                                      | awk {'print $3'}`"
  fi
  ni_line "Username......: `whoami`"
  if [ $DIST != "darwin" ] ; then
    virt=$(systemd-detect-virt)
    ni_line "Virtual.......: $virt"
    ni_line "Groups........:`groups $(whoami) | cut -f2 -d':'`"
    ni_line "Processor(s)..: $PNUMS $PVENDOR ${PMHZ} MHz ${PMODEL} ${CPUTMP}"

    ni_line "SELinux.......: `/usr/sbin/getenforce`"
    ni_line "last login....: $(last -1 -R  $USER | head -1 | cut -c 20-| awk '{$1=$1};1')"
  fi
  ni_line "menv version..: $(menv_version)"
}
