#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

# Sets up ssh priv keys
menv_function add_priv_key
function add_priv_key {
  local remoteserver=$1
  local remoteuser=${2:-`whoami`}
  local pubkeyfile=~/.ssh/id_rsa.pub
  local authkeyfile=~/.ssh/authorized_keys

  if [ ! -f $pubkeyfile ]; then
    ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa
  fi

  ssh-copy-id -i $pubkeyfile $remoteuser@$remoteserver
  #cat $pubkeyfile | ssh $remoteuser@$remoteserver "cat >> $authkeyfile"
  chmod 700 ~/.ssh
  chmod 644 $pubkeyfile
  chmod 600 ~/.ssh/id_rsa
}

menv_function magic_open
function magic_open {
  local dir=$1

  sudo chmod -R 777 $dir
}

menv_alias kill_vpn="sudo pkill -9 openvpn"

menv_function ovpn
function ovpn {
  local username="$1"
  local ovpn_cfg="$2"
  local password=""

  echo -n Password:
  read -s password
  echo

  sudo expect << DONE
    #!/usr/bin/expect -f

    set username "$username"
    set password "$password"

    set timeout 10
    spawn openvpn --config $ovpn_cfg --script-security 2 --user nobody
    expect {
      "Enter Auth Username:" {
        send "\${username}\r"
        exp_continue
      }
      "Enter Auth Password:" {
        send "\${password}\r"
        exp_continue
      }
      timeout {
      }
    }
    set timeout -1
    expect "errordne"
    send_user "openvpn terminated"
DONE
}

menv_function add_ca_trust_anchor
function add_ca_trust_anchor {
  local site=$1
  openssl s_client -showcerts -connect ${site}:443 </dev/null 2>/dev/null |
    openssl x509 -outform PEM |
    sudo tee /etc/pki/ca-trust/source/anchors/certificate_${site}.pem
  sudo update-ca-trust
}

menv_alias generate_password="pwgen  -N 1 15 -y"
