#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

menv_alias count_files_in_directory_r="find . -type f | wc -l"

# A function to list a directory structure in a nice tree.
menv_function tree_list
function tree_list {
  ls -R $1 | grep ":$" \
    | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
}

menv_function start_vm
function start_vm {
  local vm=$1
  if VBoxManage list runningvms |grep -q $vm ; then
    echo "vm already running"
  else
    VBoxManage startvm $vm --type headless
  fi
}

menv_function stop_vm
function stop_vm {
  local vm = $1
  VBoxManage controlvm $vm poweroff
}

# A function to grep excluding something I normally don't care about.
menv_function mgrep
function mgrep {
  grep -rn $1 $2 |grep -v .svn |grep -v Binary |grep -v .git
}

# Finds a program in the path which contains part of the given string.
menv_function findprogram
function findprogram {
  ls $(echo $PATH:/sbin:/usr/sbin | sed "s/:/\ /g") | grep "$1" \
    | sort --unique
}

menv_function find_large_files
function find_large_files {
  find / -type f -size +100000k -exec ls -lh {} \; | awk '{ print $9 ": " $5 }'
}

# Function that appends to the end of a file.
menv_function append_to_file
function append_to_file {
  echo $1 >> $2
}

# A fucntion to swap two files.
menv_function swap
function swap() {
  local tmp`mktemp`
  mv "$1" $tmp
  mv "$2" "$1"
  mv $tmp "$2"
}

# Diffs two urls/files.
menv_function urldiff
function urldiff {
  if [[ $1 == http* ]] ; then
    local file1=`mktemp`
    fetch $1 $file1
  else
    local file1=$1
  fi

  if [[ $2 == http* ]] ; then
    local file2=`mktemp`
    fetch $2 $file2
  else
    local file2=$2
  fi

  diff $file1 $file2
  local ret=$?

  if [[ $1 == http* ]] ; then
    $BINRM $file1
  fi

  if [[ $2 == http* ]] ; then
    $BINRM $file2
  fi

  return $ret
}

menv_function cat_all_files_in_dir
function cat_all_files_in_dir {
  find $1 -type f -exec /bin/cat '{}' \;
}

# Simple hack function to diff the file contents recursively of two folders.
menv_function lsdiff
function lsdiff {
  ls -R $1 |grep -v "\/" &> /tmp/ls1.diff
  ls -R $2 |grep -v "\/" &> /tmp/ls2.diff
  local tmp1=`mktemp`
  local tmp2=`mktemp`
  diff $tmp1 $tmp2
  $BINRM $tmp1 $tmp2
}

menv_function find_and_replace_all
function find_and_replace_all {
  local search_pattern=$1
  local replace_pattern=$2
  local dir=${3:-./}

  find $dir -type f -and -not -path "*.git*" \
    -exec sed -i -e "s/$search_pattern/$replace_pattern/g" {} \;
}

# Opens a file based on its extension or hashbang.
menv_function mopen
function mopen {
  local file="$1"

  if [ -d $file ] ; then
    nautilus "$file" &> /dev/null &
  elif [ -f $file ] ; then
    case $file in
      *.pdf) evince "$file"&> /dev/null & ;;
      *.odt) oowriter "$file" &> /dev/null & ;;
      *.ods) ooffice "$file" &> /dev/null & ;;
      *.html) google-chrome "$file" &> /dev/null & ;;
      *.dot)
        local pngfile=`mktemp --suffix==.png`
        dot_to_png $file $pngfile
        shotwell "$pngfile" &> /dev/null & ;;
      *.png|*.jpg|*.jpeg) shotwell "$file" &> /dev/null & ;;
      *.pcap|*.npcap) wireshark "$file" &> /dev/null & ;;
      *.log|*.txt|*.rej|*.patch|*.config) gedit "$file" &> /dev/null & ;;
      *)
          echo "I don't know how to open that, falling back to xdg-open!"
          xdg-open "$file"
          ;;
    esac
  else
    echo "I don't know how to open that, it is not a directory or regular file."
  fi
}

menv_function dot_to_png
function dot_to_png {
  local in=$1
  local out=$2
  dot $in -Tpng -o $2
}

menv_function convert_to_gif
function convert_to_gif {
  local files=$1
  local output=$2
  local delay=${3:-100}
  local size=${4:-640x480}
  mogrify -resize $size $files
  convert -delay $delay -loop 0 $files $output
}

menv_function topen
function topen {
  local file="$1"

  if [ -d $file ] ; then
    cd $file
  elif [ -f $file ] ; then
    case $file in
      *.dot)
        local pngfile=`mktemp`
        dot_to_png $file $pngfile
        python -m fabulous.image "$pngfile" ;;
      *.png|*.jpg|*.jpeg) python -m fabulous.image "$file"  ;;
      *.log|*.txt|*.rej|*.patch|*.cpp|*.c|*.h|*.hpp) vim "$file"  ;;
      *.html) lynx "$file" &> /dev/null & ;;
      *) echo "I don't know how to open that." ;;
    esac
  else
    echo "I don't know how to open that, it is not a directory or regular file."
  fi
}

menv_function list_root_owned_files
function list_root_owned_files {
  local dir=${1:-~}

  find $dir -uid 0
}

# This function takes a patch file and splits it into new and exisiting
# components. A new component is a sub patch which creates a new file. An
# existing component is a sub patch which edits an existing file.
menv_function split_patch_into_new_and_existing
function split_patch_into_new_and_existing {
  local patch=$1

  local existing=`realpath ${patch/\.patch/}_existing.patch`
  local new=`realpath ${patch/\.patch/}_new.patch`

  touch $existing
  touch $new

  pushd .

  local splitdir=`mktemp -d`
  local patch_part=${1}.part

  splitdiff -a $patch

  for file in $patch_part* ; do
    tmpfile=`mktemp`
    if grep "\-\-\- /dev/null" $file &> /dev/null ; then
      dst=$new
    else
      dst=$existing
    fi
    cat $file $dst &> $tmpfile
    mv -f $tmpfile $dst
  done

  popd
}

menv_function unix_epoch
function unix_epoch {
  date +%s
}

menv_function set_brightness
function set_brightness {
  local brightness=${1:-100}
  sudo bash -c "echo $brightness > /sys/class/backlight/intel_backlight/brightness"
}

menv_function pretty_print_json
function pretty_print_json {
  local json=$1
  local tmp_file=`mktmp`

  cat $json  | python -m json.tool &> $tmp_file
  mv -b $tmp_file $json
}

menv_function remove_empty_dirs
function remove_empty_dirs {
  local dir=${1:-.}

  find $dir -type d -empty -exec rmdir {} \;
}

menv_function sum_transfer_size
function sum_transfer_size {
  local file=$1

  awk '{print $3}' $file | sed 's/KB/000/' | sed 's/MB/000000/' | \
    grep -v - | grep -v % | awk '{ sum += $1 } END { print sum }'
}

menv_function save
function save {
  local savefile=${1:-$menv_local_save_dir/saveme}

  if [ -f $savefile ] ; then
    $BINCP --backup=numbered ${savefile}{,.bak}
  fi

  local input=$(cat)

  echo $input | tee $savefile
}

menv_alias dropboxd="~/.dropbox-dist/dropboxd"

menv_function determine_filesystem
function determine_filesystem {
  local dev=${1:-sd1}

  sudo fdisk /dev/$dev -l
}

menv_function grep_exclude_list
function grep_exclude_list {
  local pattern=$1

  local cmd="/usr/bin/grep -rn $pattern ."
  for param in ${*:2} ; do
    cmd="$cmd | grep -v $param "
  done
  echo $cmd
  eval $cmd
}

menv_function what
function what {
  local OUT=`which $@ 2> /dev/null`
  if [ $? -eq 0 ]; then
    echo $OUT
  fi

  OUT=`type $@ 2> /dev/null`
  if [ $? -eq 0 ]; then
    echo $OUT
  fi

  OUT=`alias $@ 2> /dev/null`
  if [ $? -eq 0 ]; then
    echo $OUT
  fi
}

menv_function list_path_permissions
function list_path_permissions {
  local file=$1
  local dir=$file

  while true ; do
    ls -altZd $dir
    if [ "$dir" = "/" ] ; then
        break;
    fi
    dir=$(realpath `dirname $dir`)
  done
}

menv_function find_ext
function find_ext {
  local ext=$1
  local dir=${2:-.}

  find $dir -iname "*.$ext"
}

menv_function talk
function talk {
  local mode=$1
  local text=$2

  case $mode in
    festival) echo "$text" | festival --tts ;;
    spd) spd-say "$text" ;;
    espeak|*) espeak "$text" ;;
  esac
}

menv_function find_all_videos
function find_all_videos {
  EXTS=(mov mp4 avi mpeg mkv flv wmv)
  for ext in "${EXTS[@]}" ; do
    find . -type f -iname "*.$ext"
  done
}

menv_function scp_all_videos
function scp_all_videos {
  local dst=$1

  EXTS=(mov mp4 avi mpeg mkv flv wmv)
  mkdir -p ~/movs
  for ext in "${EXTS[@]}" ; do
    find . -type f -iname "*.$ext" -exec cp {} ~/movs \;
  done
  scp -r ~/mov $2
}

menv_function enumerate_output
function enumerate_output {
"$@" 2> >(sed 's/^/2: /') > >(sed 's/^/1: /')
}

menv_function sshp
function sshp {
  local i=60
  while [[ $i -ne 0 ]] ; do
    ssh $*
    if [[ $? -eq 0 ]] ; then
      break
    fi
    ((--i))
    sleep 1
  done
}

menv_function cut_file_between
function cut_file_between {
  local file=$1
  local start=$2
  local end=$3
  sed -n "${start},${end}p" $file
}

menv_function checksum_dir
function checksum_dir {
  tar -cf - $1 | md5sum
}

menv_function frequency
function frequency {
  local file=$1
  awk -F ' ' '{print $1}' $file | sort | uniq -c | sort -nr
}

menv_function run_remote_script
function run_remote_script {
  local ip=$1
  local script=$2

  ssh -x -tt $ip << EOF
    $script
    exit 0
EOF
}

menv_function merge_pdfs
function merge_pdfs {
  local out=$1
  shift

  gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$out.pdf $@
}

menv_function what_file_in_transfer
function what_file_in_transfer {
  local dir=$1
  local last_file=$2
  ls -R $dir|grep "$last_file" -B 10000000 |wc -l
}
