#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if test -x "$(command -v "gnome-terminal")" ; then
# Only run gnome for gnome <= 3.8.4
gnomeVersion="$(expr "$(gnome-terminal --version)" : '.* \(.*[.].*[.].*\)$')"
if version_ge $gnomeVersion "3.8.4" ; then

spushd .

cd ~

function rm_app {
  local app="${1}.desktop"
  if [ -f .local/share/applications/${app} ] ; then
    $BINRM .local/share/applications/${app}
  fi
}

if [ $MENV_ROOT_ACCESS -ne 0 ] ; then
  sudo chattr -i ~/.local/share/recently-used.xbel
  sudo $BINRM ~/.local/share/recently-used.xbel
fi

rm_app root-wireshark
rm_app gnome-start
gsettings set org.gnome.shell favorite-apps "['gnome-terminal.desktop']"

unset rm_app

if_symlink_rm ~/.config/gtk-3.0/settings.ini

spopd

fi

fi

