#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

spushd .

cd ~

if_symlink_rm .vimrc
  
if [ -f ~/.vim/.$menv_gen_tag ] ; then
  $RM -rf ~/.vim
else
  echo "vim folder was not menv generated, not deleting!"
fi

spopd

