#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved
# requirements gnome >= 3.8.4, desktop != 0

mkdir -p ~/.config/gtk-3.0/
safe_symlink ~/.config/gtk-3.0/settings.ini $menv_dotfiles_dir/config/gtk-3.0/settings.ini

if [ -f ~/.local/share/recently-used.xbel ] ; then
  sudo chattr -i ~/.local/share/recently-used.xbel
fi
echo "" | sudo tee ~/.local/share/recently-used.xbel > /dev/null
sudo chattr +i ~/.local/share/recently-used.xbel

gsettings set org.gnome.desktop.background picture-options "scaled"

append_crontab "@reboot /home/$USER/menv/bin/mute_volume"
append_crontab "@hourly /home/$USER/menv/bin/desktop/rotate_background"

~/menv/bin/desktop/rotate_background

# TODO move into repo
avatar=david_bond_social_media.jpg
fetch http://mokonphotography.com/wp-content/uploads/2015/01/$avatar

dbus-send --system --dest=org.freedesktop.Accounts  \
    --type=method_call --print-reply \
    /org/freedesktop/Accounts/User$(id -u) \
    org.freedesktop.Accounts.User.SetIconFile \
    string:"$avatar" &> /dev/null
$BINRM $avatar

cd ~

FAV_APPS="['gnome-terminal.desktop', 'wireshark.desktop', 'virtualbox.desktop', 'virt-manager.desktop', 'nautilus.desktop', 'cheese.desktop', 'gedit.desktop', 'google-chrome.desktop', 'firefox.desktop', "
function add_app {
  local app="${1}.desktop"
  cp $menv_dotfiles_dir/local/share/applications/${app} .local/share/applications/${app}
  FAV_APPS="$FAV_APPS '${app}',"
}

mkdir -p $menv_dotfiles_dir/local/share/applications/
add_app gnome-start
gsettings set org.gnome.shell favorite-apps "${FAV_APPS%?}]"

unset add_app

# gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.nautilus.preferences always-use-location-entry  true
gsettings set org.gnome.Terminal.Legacy.Settings new-terminal-mode 'tab'
gsettings set org.gnome.gnome-screenshot auto-save-directory $menv_screenshots_dir
gsettings set org.gnome.desktop.interface clock-format '12h'
gsettings set org.gnome.SessionManager logout-prompt false
gsettings set org.gnome.desktop.interface clock-show-date true

gnomeVersion="$(expr "$(gnome-terminal --version)" : '.* \(.*[.].*[.].*\)$')"
if ! version_ge $gnomeVersion "3.22.1" ; then
  gsettings set org.gnome.shell.calendar show-weekdate true
fi
gconftool-2 -t int --set /apps/gnome-terminal/profiles/Default/scrollback_lines 100000
gsettings set org.gnome.shell.overrides workspaces-only-on-primary false

gset_powr_path=org.gnome.settings-daemon.plugins.power
if version_ge $gnomeVersion "3.22.1" ; then
  gsettings set $gset_powr_path power-button-action hibernate
else
  gsettings set $gset_powr_path button-power hibernate
fi
gsettings set $gset_powr_path sleep-inactive-ac-timeout      36000
gsettings set $gset_powr_path sleep-inactive-ac-type         hibernate
gsettings set $gset_powr_path sleep-inactive-battery-timeout 18000
gsettings set $gset_powr_path sleep-inactive-battery-type    hibernate
gsettings set org.gnome.desktop.lockdown disable-lock-screen true
# gsettings set org.gnome.settings-daemon.plugins.xrandr default-monitors-setup do-nothing
gsettings set org.gnome.gedit.preferences.ui max-recents "uint32 0"

echo "Setting plymouth theme"
sudo plymouth-set-default-theme solar -R &> /dev/null

alias record_screen="echo 'Type Ctrl + Shift + Alt + R'"

PALETTE="['rgb(0,0,0)', 'rgb(205,0,0)', 'rgb(0,205,0)', 'rgb(205,205,0)', 'rgb(30,144,255)', 'rgb(205,0,205)', 'rgb(0,205,205)', 'rgb(229,229,229)', 'rgb(76,76,76)', 'rgb(255,0,0)', 'rgb(0,255,0)', 'rgb(255,255,0)', 'rgb(70,130,180)', 'rgb(255,0,255)', 'rgb(0,255,255)', 'rgb(255,255,255)']"
BG_COLOR="rgb(0,0,0)"
FG_COLOR="rgb(0,255,0)"
BD_COLOR="#9393a1a1a1a1"

p="/org/gnome/terminal/legacy/profiles:/"
profiles=($(dconf list $p | grep ^: | sed 's/\///g'))
for i in ${!profiles[*]} ; do
  if [[ "$(dconf read $p${profiles[i]}/visible-name)" == "'Default'" ]] ; then
    uuid="${profiles[i]}"
  fi
done
p="$p$uuid"
dconf write ${p}palette "[$PALETTE]"

dconf write ${p}bold-color "'$BD_COLOR'"
dconf write ${p}background-color "'$BG_COLOR'"
dconf write ${p}foreground-color "'$FG_COLOR'"

dconf write ${p}use-theme-colors "false"
dconf write ${p}use-theme-background "false"
dconf write ${p}bold-color-same-as-fg "false"

dconf write ${p}scrollback-unlimited "true"

p="/apps/gnome-terminal/profiles/Default"
gconftool-2 --set "$p/use_theme_background" --type bool false
gconftool-2 --set "$p/use_theme_colors" --type bool false
gconftool-2 --set "$p/palette" --type string "$PALETTE"
gconftool-2 --set "$p/background_color" --type string "$BG_COLOR"
gconftool-2 --set "$p/foreground_color" --type string "$FG_COLOR"

if [ ! -f  ~/.Xauthority ] ; then
  xauth add :0 . `mcookie` | grep -v "does not exist"
fi

if [ ! -z $MENV_HOSTNAME ] ; then
  sudo hostnamectl set-hostname --static "$MENV_HOSTNAME"
  sudo hostnamectl set-hostname --pretty "$MENV_HOSTNAME"
fi
