#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if [ $MENV_DESKTOP -ne 0 ] ; then

macroSecurityLevelXPath='//oor:items/item[@oor:path="/org.openoffice.Office.Common/Security/Scripting"]/prop[@oor:name="MacroSecurityLevel"]'
ooconfig=/home/$USER/.config/libreoffice/4/user/registrymodifications.xcu

xmlstarlet ed -L -u  ${macroSecurityLevelXPath} -v 2 ${ooconfig}

fi
