#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved
# requirements dist != darwin, desktop != 0

if [ -f /etc/selinux/config ] ; then
  sudo cp /etc/selinux/config $menv_sysbackup_dir
fi

sudo setenforce 0 &> /dev/null

cat <<HEREDOC | sudo tee /etc/selinux/config &> /dev/null
SELINUX=disabled
SELINUXTYPE=targeted
HEREDOC
