#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

menv_alias menv_help="cat ~/menv/README | less"
menv_alias sudo='sudo ' # Allow sudo to be used on aliases.
menv_alias rm='mv --target-directory ~/trash'
menv_alias delete_immediately='/bin/rm -Rf'
menv_alias di='/bin/rm -Rf'
menv_alias empty_trash='/bin/rm -rf ~/trash/*'
menv_alias empty_dl='/bin/rm -rf ~/Downloads/*'
menv_alias empty_all='/bin/rm -rf ~/trash/* ; /bin/rm -rf ~/Downloads/* ; /bin/rm -rf ~/.local/share/Trash/'
menv_alias mv='mv -i'
menv_alias psa="ps -aux"
menv_alias e="exit"
menv_alias ex="exit"
menv_alias exi="exit"
menv_alias ls="ls --color"
menv_alias bx="source ~/.bashrc"
menv_alias mvbk="/bin/mv --backup=numbered"
menv_alias cpbk="/bin/cp --backup=numbered"
menv_alias remote_terminal_share="wemux"
menv_alias delallswap="/bin/rm *.swp"
menv_alias fkill="sudo kill -9"
menv_alias less="less -R"
menv_alias grep="grep --color=always"
menv_alias what_time_is_it="date +%I:%M"
menv_alias folders_sizes="du -sh *"

