#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

# Aux function to test if a command exists.
menv_function bash_cmd_exists
function bash_cmd_exists {
    test -x "$(command -v "$1")"
}

menv_alias show_bash_functions="typeset -f"
menv_alias show_bash_function="type"
menv_alias list_bash_functions="typeset -F"

