#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function senddiff {
  subject=${1:-diff}
  to=${2:-mokon@mokon.net}
  tmpfile=`mktemp`
  git diff &> $tmpfile
  sendemail $tmpfile "$subject" "$to"
  rm $tmpfile
}

function sendemail {
  file=$1
  subject=${2:-$file}
  to=${3:-mokon@mokon.net}
  cat $file | mail -s "$subject" -r mokon@mokon.net $to mokon@mokon.net
}
