#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

if test -x "$(command -v "gnome-terminal")" ; then
# Only run gnome for gnome <= 3.8.4
gnomeVersion="$(expr "$(gnome-terminal --version)" : '.* \(.*[.].*[.].*\)$')"
if version_ge $gnomeVersion "3.8.4" ; then

menv_function gstart
function gstart {
  source $menv_bin_dir/gnome_start
}

menv_function gnome_add_tab
function gnome_add_tab {
  WID=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)"| awk '{print $5}')
  xdotool windowfocus $WID
  xdotool key ctrl+shift+t
  wmctrl -i -a $WID
}

menv_function gnome_list_all_settings
function gnome_list_all_settings {
  for schema in $(gsettings list-schemas | sort) ; do
    for key in $(gsettings list-keys $schema | sort) ; do
      value="$(gsettings range $schema $key | tr "\n" " ")"
      echo "$schema :: $key :: $value"
    done
  done
}

fi
fi
