#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if test -x "$(command -v "gnome-terminal")" ; then
# Only run gnome for gnome <= 3.8.4
gnomeVersion="$(expr "$(gnome-terminal --version)" : '.* \(.*[.].*[.].*\)$')"
if version_ge $gnomeVersion "3.8.4" ; then

menv_function gstart
function gstart {
  source $menv_bin_dir/gnome_start
}

menv_function gnome_add_tab
function gnome_add_tab {
  WID=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)"| awk '{print $5}')
  xdotool windowfocus $WID
  xdotool key ctrl+shift+t
  wmctrl -i -a $WID
}

menv_function gnome_list_all_settings
function gnome_list_all_settings {
  for schema in $(gsettings list-schemas | sort) ; do
    for key in $(gsettings list-keys $schema | sort) ; do
      value="$(gsettings range $schema $key | tr "\n" " ")"
      echo "$schema :: $key :: $value"
    done
  done
}

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  eval `dbus-launch --close-stderr --sh-syntax --exit-with-session`
  #export $(dbus-launch)
fi

menv_alias rd="rdesktop -g 1600x900 -u admin -p -"

menv_alias mount_phone="simple-mtpfs $menv_local_dir/phone"
menv_alias unmount_phone="fusermount -u $menv_local_dir/phone"

fi

fi

