#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function plot {
  local infile=${1}
  local outfile=${2:-`mktemp --suffix .png`}

  local plotfile=`mktemp`

  cat <<-EOF > $plotfile
    set term png
    set output "${outfile}"
    plot "$infile" using 1:2 with lines
EOF

  gnuplot $plotfile
  shotwell "$outfile" &> /dev/null

  rm $plotfile
}
