#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

menv_function convert_base
function convert_base {
  local from=$1
  local to=$2
  local number=$( to_upper ${3})

  echo "obase=$to; ibase=$from; $number" | bc
}

menv_alias dec_to_binary="convert_base 10 2 "
menv_alias binary_to_dec="convert_base 2 10 "
menv_alias dec_to_hex="convert_base 10 16 "
menv_alias hex_to_dec="convert_base 16 10 "

menv_function hex_endian_conversion
function hex_endian_conversion {
  local hex=$1
 
  echo ${hex:6:2}${hex:4:2}${hex:2:2}${hex:0:2}
}

menv_function dec_endian_conversion
function dec_endian_conversion {
  hex_endian_conversion `dec_to_hex $1`
}

menv_function binary_endian_conversion
function binary_endian_conversion {
  hex_endian_conversion `binary_to_hex $1`
}

menv_function binary_to_hex
function binary_to_hex {
  local binary=$1

  local dec=$(binary_to_dec $binary)

  dec_to_hex $dec
}

menv_function hex_to_binary
function hex_to_binary {
  local hex=$1

  local dec=$(hex_to_dec $hex)

  dec_to_binary $hex
}

menv_function to_lower
function to_lower {
  local input=$1

  echo $input | awk '{print tolower($0)}'
}

menv_function to_upper
function to_upper {
  local input=$1

  echo $input | awk '{print toupper($0)}'
}

menv_function calc
function calc {
  echo "$*" | bc
}

