#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

menv_function convert_base
function convert_base {
  local from=$1
  local to=$2
  local number=$3

  echo "obase=$to; ibase=$from; $number" | bc
}

menv_alias dec_to_binary="convert_base 10 2 "
menv_alias binary_to_dec="convert_base 2 10 "
menv_alias dec_to_hex="convert_base 10 16 "
menv_alias hex_to_dec="convert_base 16 10 "

menv_function calc
function calc {
  echo "$*" | bc
}

