#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

alias menv_help="cat ${menv_dir}/README | less"
function menv_vault_refresh {
  source ~/.bash_profile
}

# Simple function for my dev box which has menv checked out in git. This
# allows me to test menv on the box before I push it to github.
if [ -d ~/menv/vault/code/menv ]; then
  function menv_stage {
    spushd .

    menv_uninstall

    cd ~
    /bin/cp -R  ~/vault/code/menv ~
    /bin/rm -rf ~/menv/.git
    find menv/ -not -path "menv/vault/*/*" -and -name .gitkeep -exec rm -rf {} \;

    source ~/menv/core/target_handler

    menv_version ignore

    source ~/menv/core/login

    spopd
  }
fi

function make_menv_home_dirs {
  for dir in pics docs code; do
    mkdir $menv_vault_dir/$dir
    safe_symlink ~/$dir $menv_vault_dir/$dir
  done
}

function menv_clone_coderef {
  spushd .

  mkdir -p ~/code/ref

  git clone git://git.sv.gnu.org/coreutils.git
  git clone https://github.com/git/git.git
  git clone git://sourceware.org/git/glibc.git
  git clone https://github.com/torvalds/linux.git
  git clone https://github.com/USCiLab/cereal.git
  git clone https://github.com/libgit2/libgit2.git
  git clone git://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git
  git clone https://gerrit.googlesource.com/gerrit
  git clone git://gcc.gnu.org/git/gcc.git
  git clone https://github.com/FRRouting/frr
  git clone https://git.torproject.org/git/tor
  git clone https://ezix.org/src/pkg/lshw

  spopd
}

alias menv_grep="grep --exclude-dir trash --exclude-dir vault --exclude-dir cache"
alias menv_line_count="find . -type f -exec file {} + | grep -v "./cache\|npm_modules\|./trash\|./cache\|./git" | awk -F: '/ASCII text/ {print \$1}'|xargs wc -l"
