#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

menv_alias menv_help="cat ${menv_dir}/README | less"
menv_alias menv_local_refresh="source ~/.bash_profile"

# Simple function for my dev box which has menv checked out in git. This
# allows me to test menv on the box before I push it to github.
if [ -d ~/git/menv ]; then
  menv_function menv_stage
  function menv_stage {
    spushd .
  
    menv_uninstall
    
    cp -R  ~/git/menv ~

    source ~/menv/core/target_handler

    menv_version staged

    spopd
  }
fi

