#!/bin/bash
# (C) 2017 David 'Mokon' Bond, All Rights Reserved

function install_module {
  module_name=$1
  module_url=$2

  if [ ! -d ~/menv/cache/$module_name ] ; then
    cd ~/menv/cache
    git clone -q $module_url $module_name
  fi

  if [ ! -f ~/menv/dotfiles/vimrc_style/${module_name}.vim ] ; then
    ln -s ~/menv/cache/${module_name}/*/${module_name}.vim \
      ~/menv/dotfiles/vimrc_style/${module_name}.vim
  fi
  menv_export CODING_STYLE=${module_name}
}
