#!/bin/bash
# (C) 2017 David 'Mokon' Bond, All Rights Reserved

function install_module {
  local module_name=$1
  local module_url=$2

  if [ ! -d ~/menv/cache/${module_name} ] ; then
    spushd .
    cd ~/menv/cache
    echo "Installing module ${module_name}. Git Hub login may be required."
    git clone -q ${module_url} ${module_name}
    spopd
  fi

  if [ ! -f ~/menv/dotfiles/vimrc_style/${module_name}.vim ] ; then
    ln -s ~/menv/cache/${module_name}/dotfiles/${module_name}.vim \
      ~/menv/dotfiles/vimrc_style/${module_name}.vim
  fi
  menv_export CODING_STYLE=${module_name}

  source ~/menv/cache/${module_name}/dotfiles/bashrc
  export PATH=$PATH:~/menv/cache/${module_name}/bin/
}
