#!/bin/bash
# (C) 2017 David 'Mokon' Bond, All Rights Reserved

function install_module {
  local module_name=$1
  local module_url=$2

  local cache_module_dir=${menv_cache_dir}/${module_name}
  local cache_vimrc_style=${menv_cache_vimrc_style_dir}/${module_name}.vim
  local module_vimrc_style=${cache_module_dir}/dotfiles/${module_name}.vim

  if [ ! -d ${cache_module_dir} ] ; then
    spushd .
    cd ${menv_cache_dir}
    echo "Installing module ${module_name}. Git Hub login may be required."
    git clone -q ${module_url} ${module_name}
    spopd
  fi

  if [ ! -f ${cache_vimrc_style} ] ; then
    mkdir -p ${menv_cache_vimrc_style_dir}
    ln -s ${module_vimrc_style} ${cache_vimrc_style}
  fi
  menv_export CODING_STYLE=${module_name}

  source ${cache_module_dir}/dotfiles/bashrc
  export PATH=$PATH:${cache_module_dir}/bin/
}
