#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

alias download_youtube_video="youtube-dl"

function stream_youtube {
  local url=$1
  youtube-dl $url -o - | mplayer -vo aa -monitorpixelaspect 0.5 -
}

function stream_youtube_text {
  local url=$1
  youtube-dl $url -o - | CACA_DRIVER=ncurses mplayer -cache 64000 -vo caca -
}
