#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

# Networking aliases and functions
menv_alias arp_flush="ip -s -s neigh flush all"
menv_alias amialone="ping 8.8.8.8"
menv_alias amialonedns="ping google.com"

# A function which looks up a ethertype
menv_function ethertype
function ethertype {
  local etypein_dec=`printf %d $1`
  local etypein_hex=`printf %03x $1`

  local file=${menv_cache_dir}/ethertype
  if [ ! -f $file ]; then
    url=https://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers-1.csv
    wget -O $file -q $url
  fi

  local OLDIFS=$IFS
  IFS=,
  shopt -s nocasematch
  while read etype_dec etype_hex exp_enet_dec exp_enet_octal desc ref ; do
    if [[ $etype_dec == $etypein_dec || $etype_hex == $etypein_hex ]] ; then
      echo $desc $ref
    fi
  done < $file
  shopt -u nocasematch
  IFS=$OLDIFS
}

menv_function dec_to_ip
function dec_to_ip {
  local ip dec=$@
  for e in {3..0} ; do
    ((octet = dec / (256 ** e) ))
    ((dec -= octet * 256 ** e))
    ip+=$delim$octet
    delim=.
  done
  printf '%s\n' "$ip"
}

menv_function ip_to_dec
function ip_to_dec {
  local a b c d ip=$@
  IFS=. read -r a b c d <<< "$ip"
  printf '%d\n' "$((a * 256 ** 3 + b * 256 ** 2 + c * 256 + d))"
}

menv_function hex_to_ip
function hex_to_ip {
  printf '%d.%d.%d.%d\n' `echo $@ | sed -r 's/(..)/0x\1 /g'`
}

menv_function hex_to_ip
function ip_to_hex {
  printf '%.2X%.2X%.2X%.2X\n' `echo $@ | sed -e 's/\./ /g'`
}

menv_alias mcast_route_cache="cat /proc/net/ip_mr_cache"

menv_function mcast_ip6_join_ssm
function mcast_ip6_join {
  local interface=$1
  local group=$2
  local src=$3

  vlc -vvv udp://[$src]@[$group] --miface=$interface
}

menv_function mcast_ip6_join
function mcast_ip6_join {
  local interface=$1
  local group=$2

  vlc -vvv udp://@[$group] --miface=$interface
}

menv_function mcast_ip6_joins
function mcast_ip6_joins {
  local path=/proc/net/igmp6
  while read index intname address refcnt flags timer ; do
    echo "$intname is joined on group $address $refcnt times with flags $flags and timer $timer."
  done < $path
}

# A function to download an rfc and store it on the localhost. If the -l
# option is given the rfc will be opened in lynx.
menv_function rfc
function rfc {
  local ietf=http://tools.ietf.org
  local rfcdir=$menv_cache_dir/rfc
  local rfc=$1

  if [[ $2 == "-l" ]] ; then
    local extension=html
    local url=$ietf/$extension/rfc$rfc
  else
    local extension=txt
    local url=$ietf/rfc/rfc$rfc.$extension
  fi

  if [ ! -d $rfcdir ]; then
    mkdir $rfcdir
  fi

  if [ ! -f $rfcdir/$rfc.$extension ]; then
    wget -q $url -O $rfcdir/$rfc.$extension
    if [[ $? != 0 ]]; then
      $RM -f $rfcdir/$rfc.$extension
    fi
  fi

  if [ -f $rfcdir/$rfc.$extension ]; then
    if [[ $2 == "-l" ]] ; then
      lynx $rfcdir/$rfc.$extension
    else
      cat $rfcdir/$rfc.$extension | $PAGER
    fi
  else
    echo "RFC Not Found"
  fi
}

# A function to test if a connection exists to the given server.
menv_function testconnection
function testconnection {
  local server=$1
  local suc_msg=$2
  local err_msg=$3
  local dns_err_msg=$4

  ping -c1 -W1 "$server" &> /dev/null
  if [ $? ]; then
    echo $suc_msg
  else
    host -W1 $?
    if [ $? ]; then
      echo $err_msg
    else
  	  echo $dns_err_msg
    fi
  fi
}

menv_function update_host
function update_host {
  local hostname=$1
  local ip=$2
  local file=${3:-/etc/hosts}

  # If the name exists in the host file delete it.
  sudo sed -i "/ $hostname/d" $file

  # Now append the new host entry to the file
  sudo bash -c " echo '$ip $hostname' >> /etc/hosts"
}

menv_function convert_to_pcap
function convert_to_pcap {
  local file=$1
  local encap=${2:-tcp}
  local proto=${3-bgp}

  case $encap in
    tcp) encap="-T";;
      *) ;;
  esac

  case $proto in
    bgp) proto=179;;
      *) ;;
  esac

  text2pcap $encap $proto,$proto $file ${file}.pcap
  mopen ${file}.pcap
}

menv_function capture_on_interfaces
function capture_on_interfaces {
  interfaces=$1
  trace_length=${2:-420}

  for interface in ${interfaces} ; do
    tshark_pcap=capture_${interface}.pcap
    sudo tshark -q -i $interface -a duration:$trace_length -w /tmp/$tshark_pcap &
  done

  sleep $trace_length
}

