#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

menv_function nodeinfo {
function nodeinfo {
  local MEMT=`cat /proc/meminfo | grep MemTotal`
  local SWAT=`cat /proc/meminfo | grep '^SwapTotal:'`
  local PMODEL=`cat /proc/cpuinfo | \
    grep '^model name' | awk '{print $4 $5 $6}' | head -1`
  local PMHZ=`cat /proc/cpuinfo | \
    grep '^cpu MHz' | awk '{print $4}'| sed -e 's/\.[0-9]*//g' | head -1`
  local PVENDOR=`cat /proc/cpuinfo | \
    grep '^vendor_id' | awk '{print $3}' | head -1`
  local PNUMS=`cat /proc/cpuinfo | \
    grep '^processor' | wc -l | awk '{print $1}' | head -1`

  echo "OS............: `uname -o`"
  echo "Hostname......: `uname -n`"
  echo "Address(es)...: `/sbin/ifconfig | grep "inet" \
                           | grep -v '127.\|::1\|fe80::' | awk '{print $2}' \
                           | sed ':a;N;$!ba;s/\n/\n..............: /g'` "
  echo "Kernel........: `uname -s ` `uname -r` `uname -v`"
  echo "Machine HW....: `uname -m`"
  echo "Uptime........:`uptime | sed 's/.*up ([^,]*), .*/1/'`"
  echo "Memory........: `echo $MEMT | awk {'print $2'}` `echo $MEMT \
                                    | awk {'print $3'}`"
  echo "SWAP..........: `echo $SWAT | awk {'print $2'}` `echo $SWAT \
                                    | awk {'print $3'}`"
  echo "Username......: `whoami`"
  echo "Processor(s)..: $PNUMS $PVENDOR ${PMHZ} MHz ${PMODEL}"

  echo "Reachability..:"
  echo -n "..............: "
  testconnection "8.8.8.8" "Google DNS Reachable" "Google DNS Not Reachable" ""

  echo -n "..............: "
  testconnection "google.com" "Google Reachable" "Google Not Reachable" \
    "DNS Failure"

  bash_cmd_exists git # TODO update
  if [ $? ] ; then
    menv_version=`git ls-remote $menv_git_loc|grep HEAD|awk '{print $1}'`
  else
    menv_version="(unknown, install git to retrieve menv version)"
  fi
  echo "menv version..: $menv_version"
  echo -n "..............: "
  ping -c1 -W1 github.com &> /dev/null
  if [ $? ]; then
    urldiff $menv_loc ~/menv &> /dev/null
    if [ $? == 0 ]; then
      echo "menv script up to date."
    else
      echo "menv script different than github. Please upgrade."
    fi
  else
    echo "Git Hub not reachable. Could not check if menv is up to date."
  fi
}

