#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

# Sets up ssh priv keys
menv_function add_priv_key
function add_priv_key {
  local remoteserver=$1
  local remoteuser=${2:-`whoami`}
  local pubkeyfile=~/.ssh/id_rsa.pub
  local authkeyfile=~/.ssh/authorized_keys

  if [ ! -f $pubkeyfile ]; then
    ssh-keygen -t rsa 4096 -N '' -f ~/.ssh/id_rsa 
  fi
  cat $pubkeyfile | ssh $remoteuser@$remoteserver "cat >> $authkeyfile"
}

