#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

menv_function start
function start {
  local SESSION=$USER
  local WI=0
  local SELECTED_WINDOW=1

  unset TMUX

  tmux new-session -d -s $SESSION -n 'host'
  tmux send-keys  -t $SESSION:$((++WI)) "cd ~" C-m

  # tmux new-window -t $SESSION:$((++WI)) -n 'msger' "finch"

  if [ -f $menv_local_dir/tmux_start ] ; then
    source $menv_local_dir/tmux_start
  fi

  tmux select-window -t $SESSION:$SELECTED_WINDOW
  tmux attach-session -t $SESSION
}

menv_function tmux_help
function tmux_help {
cat <<HERE
  tmux new -s session_name
  tmux attach -t session_name
  tmux switch -t session_name
  tmux list-sessions
  tmux detach (prefix + d)
  tmux kill-session -t session_name
  prefix in my tmuxrc is ctrl a
HERE
}
