#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

menv_function start
function start {
  local SESSION=$USER
  local WI=1
  local SELECTED_WINDOW=1

  tmux new-session -d -s $SESSION -n 'host'
  tmux send-keys  -t $SESSION:$((WI++)) "cd ~" C-m

  tmux new-window -t $SESSION:$((WI++)) -n 'msger' "finch"


  if [ -f $menv_local_dir/tmux_start ] ; then
    source $menv_local_dir/tmux_start
  fi

  tmux select-window -t $SESSION:$SELECTED_WINDOW
  tmux attach-session -t $SESSION
}

