#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

export WEGORC=~/.wegorc
export GOPATH=$HOME/menv/go
export PATH="$PATH:$GOPATH/bin"

alias weather="telnet rainmaker.wunderground.com"
