#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

menv_function wemux_init
function wemux_init {
  sudo useradd -c "Wemux Guest" -e 1986-10-06 -f 0 -p $(crypt guest) -m -s /bin/bash guest
  sudo cp $menv_bin_dir/wemux_bash_profile ~guest/.bash_profile
  sudo chown guest ~guest/.bash_profile
  sudo chgrp guest ~guest/.bash_profile
}

menv_function wemux_open
function wemux_open {
  local ndays=${1:-1}

  sudo chage -E $(($(date --utc --date "$1" +%s)/86400+$ndays)) guest
}

