#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved
  
history -a
export HISTFILE=~/.bash_history

echo >> "$HISTFILE"
cat "${menv_history_dir}/bash_history.${BASHPID}" >> "$HISTFILE"
tmplog=`mktemp`
cat "$HISTFILE" | tail -n $HISTSIZE > $tmplog
$BINMV -f $tmplog "$HISTFILE"

if [ -f ${menv_history_dir}/bash_history.${BASHPID} ] ; then
  rm ${menv_history_dir}/bash_history.${BASHPID}
fi
