#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

cd ~

if_symlink_rm .vimrc
  
if [ -f ~/.vim/.$menv_gen_tag ] ; then
  $BINRM -rf ~/.vim
else
  echo "vim folder was not menv generated, not deleting!"
fi
