#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

function bash_cmd_exists {
    test -x "$(command -v "$1")"
}

alias show_bash_functions="typeset -f"
alias show_bash_function="type"
alias list_bash_functions="typeset -F"
