#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if [ -f $menv_dir/.$menv_gen_tag ] ; then
  echo "menv is already installed on this computer. Not installing."
else
  echo "Installing menv!"

  menv_export MENV_INTERACTIVE=1

  menv_lock $menv_dir/.lock

  touch $menv_dir/.$menv_gen_tag
  menv_version set
  spushd .

  read -t 5 -p "Is this a desktop system? " -n 1 -r
  echo

  if [[ $REPLY =~ ^[Yy]$ ]] ; then
    echo "desktop" >> $menv_install_opts_file
    menv_export MENV_DESKTOP=1

    read -t 5 -p "Please provide a hostname: " -r
    menv_export MENV_HOSTNAME="$REPLY"

local u=`whoami`
    echo "$u ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers &> /dev/null
    echo "$u ALL=(root) NOPASSWD: /sbin/reboot" | sudo tee -a /etc/sudoers &> /dev/null
    exesudo delete_line_in_file "\tDefaults    env_reset" /etc/sudoers
    exesudo delete_line_in_file "\tDefaults    secure_path = *" /etc/sudoers
  else
    echo "nodesktop" >> $menv_install_opts_file
    menv_export MENV_DESKTOP=0
  fi

  # Link the bash targets.
  cd ~
  safe_symlink $bashrc $menv_target_handler
  safe_symlink $bash_profile $menv_target_handler
  safe_symlink $bash_logout $menv_target_handler

  if [ -d ~/backup ] ; then
    echo "Restoring backup dir!"
    $BINRM -rf $menv_backup_dir
    $BINMV ~/backup $menv_backup_dir
  fi

  if [ -d ~/local ] ; then
    echo "Restoring local dir!"
    $BINRM -rf $menv_local_dir
    $BINMV ~/local $menv_local_dir
  fi

  if [ ! -f $menv_local_nonlogin ]; then
    echo "Didn't find ${menv_local_nonlogin}."
  fi

  # Link some files and dirs to the user home.
  safe_symlink ~/code $menv_local_dir/code
  safe_symlink ~/docs $menv_local_dir/docs

  if [ $MENV_DESKTOP -ne 0 ] ; then
    safe_symlink ~/pics $menv_local_dir/pics
  fi

  $BINRM -f $menv_local_dir/code/.gitkeep
  $BINRM -f $menv_local_dir/docs/.gitkeep
  $BINRM -f $menv_local_dir/pics/.gitkeep

  spopd

  menv_target_children install

  menv_unlock $menv_dir/.lock

  echo "Done installing menv!"
fi

