#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

if [ -f $menv_cache_dir/.$menv_gen_tag ] ; then
  echo "menv is already installed on this computer. Not installing."
else
  echo "Installing menv!"

  export MENV_INTERACTIVE=1

  menv_lock $menv_dir/.lock

  touch $menv_cache_dir/.$menv_gen_tag
  menv_version set
  spushd .

  read -t 60 -p "Do you have root access on this system? " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]] ; then
    echo "root" >> $menv_install_opts_file

    if [ $DIST != "darwin" ] ; then
      read -t 60 -p "Please provide a hostname: " -r
      export MENV_HOSTNAME="$REPLY"

      local u=`whoami`
      echo "$u ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers &> /dev/null
      echo "$u ALL=(root) NOPASSWD: /sbin/reboot" | sudo tee -a /etc/sudoers &> /dev/null
      ${menv_bin_dir}/exesudo delete_line_in_file "\tDefaults    env_reset" /etc/sudoers
      ${menv_bin_dir}/exesudo delete_line_in_file "\tDefaults    secure_path = *" /etc/sudoers
    fi
  else
    echo "nodesktop" >> $menv_install_opts_file
    echo "noroot" >> $menv_install_opts_file
  fi

  read -t 60 -p "Is this a desktop system? " -n 1 -r
  echo

  if [[ $REPLY =~ ^[Yy]$ ]] ; then
    echo "desktop" >> $menv_install_opts_file
  else
    echo "nodesktop" >> $menv_install_opts_file
  fi

  read -t 60 -p "Do you want to install packages MENV might use? " -n 1 -r
  echo

  if [[ $REPLY =~ ^[Yy]$ ]] ; then
    echo "pkgs" >> $menv_install_opts_file
  else
    echo "nopkgs" >> $menv_install_opts_file
  fi

  menv_load_install_opts

  # Link the bash targets.
  cd ~
  echo "Linking bash dotfiles"
  safe_symlink $bashrc $menv_target_handler
  safe_symlink $bash_profile $menv_target_handler
  safe_symlink $bash_logout $menv_target_handler

  if [ -d ~/vault ] ; then
    echo "Restoring vault dir!"
    $BINRM -rf $menv_vault_dir
    $BINMV ~/vault $menv_vault_dir
  fi

  if [ ! -f $menv_vault_nonlogin ]; then
    echo "Didn't find ${menv_vault_nonlogin}."
  fi

  # Link some files and dirs to the user home.
  safe_symlink ~/code $menv_vault_dir/code
  safe_symlink ~/docs $menv_vault_dir/docs

  if [ $MENV_DESKTOP -ne 0 ] ; then
    safe_symlink ~/pics $menv_vault_dir/pics
  fi

  $BINRM -f $menv_vault_dir/code/.gitkeep
  $BINRM -f $menv_vault_dir/docs/.gitkeep
  $BINRM -f $menv_vault_dir/pics/.gitkeep
  mkdir ${menv_cache_bin_dir}

  spopd

  if [ $MENV_ROOT -ne 0 ] ; then
    menv_target_children install_global
  fi
  menv_target_children install_user

  menv_unlock $menv_dir/.lock

  echo "Done installing menv!"
fi
