#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if [[ "$MENV_INTERACTIVE" == 1 ]] ; then
  echo "Starting menv"
else 
  echo "not iteractive"
fi

menv_target_children nonlogin

export PATH=$PATH:$HOME/bin:$menv_bin_dir:$HOME/.local/bin

if [ -d $menv_local_bin_dir ];then
  export PATH=$PATH:$HOME/bin:$menv_local_bin_dir
fi

if [[ "$MENV_INTERACTIVE" == 1 ]] ; then

menv_target_children login

# Check the script version and update if needed. Never update an ignore version.
testconnection github.com &> /dev/null
if [ $? ]; then
  if [ "$(menv_version get)" == "ignore" ] ; then
    echo "menv script ignored." &> $menv_logs_dir/menv_status
  elif [ "$(menv_version get)" == "$(menv_latest_version)" ] ; then
    echo "menv script up to date." &> $menv_logs_dir/menv_status
  else
    if [ -f $menv_last_no_update_file ] ; then
      find $menv_last_no_update_file -mtime +10 -type f -delete
    fi
    if [ ! -f $menv_last_no_update_file ] ; then
      read -t 5 -p "menv script different than github. update? " -n 1 -r
      echo

      if [[ $REPLY =~ ^[Yy]$ ]] ; then
        echo "menv script different than github. Auto-updating." | tee $menv_logs_dir/menv_status
        menv_target update
      else
        touch $menv_last_no_update_file
        echo "menv script different than github. Not-updating" | tee $menv_logs_dir/menv_status
        echo
      fi
    else
      echo "menv script different than github. Not-updating, since recently update rejected." | tee $menv_logs_dir/menv_status
      echo "run menv_update if you wish to manually update" | tee $menv_logs_dir/menv_status
    fi
  fi
else
  echo "Git Hub not reachable. Could not check if menv is up to date." | tee $menv_logs_dir/menv_status
fi


# Source a local nonlogin script if one exists.
if [ -f $menv_local_nonlogin ]; then
  source $menv_local_nonlogin
fi

fi

# Source global definitions
if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

if [[ "$MENV_INTERACTIVE" == 1 ]] ; then
  echo "printing motd"
  source $menv_core_dir/motd
else
  echo "no motd"
fi

