#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

echo "Uninstalling menv"

menv_lock $menv_dir/.lock

source ~/.bash_logout

spushd .

cd ~

menv_version ignore
menv_target login &> /dev/null # So we have the aliases etc in the menv arrays.

menv_target_children uninstall

local u=`whoami`
exesudo delete_line_in_file "$u ALL=(ALL) NOPASSWD: ALL" /etc/sudoers
exesudo delete_line_in_file "$u ALL=(root) NOPASSWD: \/sbin\/reboot" /etc/sudoers

if_symlink_rm $bashrc
if_symlink_rm $bash_profile
if_symlink_rm $bash_logout

if_symlink_rm ~/cloud
if_symlink_rm ~/docs
if_symlink_rm ~/code
if_symlink_rm ~/pics

echo "Saving the menv backup and local directories."
$BINMV $menv_backup_dir ~
$BINMV $menv_local_dir ~

echo "Deleting the menv directory."
$BINRM -rf $menv_dir

spopd

for menv_export in "${menv_exports[@]}" ; do
  unset "$( echo $menv_export | cut -f1 -d "=")"
done
unset menv_exports

for menv_alias in "${menv_aliases[@]}" ; do
  unalias "$( echo $menv_alias | cut -f 1 -d "=")"
done
unset menv_aliases

for menv_func in "${menv_funcs[@]}" ; do
  unset $menv_func
done
unset menv_funcs

if [ -f /etc/skel/.bashrc ] ; then
  cp /etc/skel/.bashrc .
fi

if [ -f /etc/skel/.bash_profile ] ; then
  cp /etc/skel/.bash_profile .
fi

if [ -f /etc/skel/.bash_logout ] ; then
  cp /etc/skel/.bash_logout .
fi

/bin/rm -f ~/menv/.lock

echo "Uninstalling menv done"

