#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

echo "Uninstalling menv"

menv_lock $menv_dir/.lock

. ~/.bash_logout

spushd .

cd ~

menv_version ignore

menv_load_install_opts

menv_target_children uninstall_user
if [ $MENV_ROOT -ne 0 ] ; then
  menv_target_children uninstall_global
fi

if_symlink_rm $bashrc
if_symlink_rm $bash_profile
if_symlink_rm $bash_logout

if_symlink_rm ~/docs
if_symlink_rm ~/code
if_symlink_rm ~/pics

$BINCP /etc/hosts $menv_backup_dir

echo "Saving the menv backup and vault directories."
$BINMV $menv_backup_dir ~
$BINMV $menv_vault_dir ~

if ! find ~/backup -mindepth 1 -print -quit | grep -q .; then
  echo "Deleting empty backup directory."
  $BINRM -rf ~/backup
fi

$BINRM -rf $menv_dir

spopd

if [ -f /etc/skel/.bashrc ] ; then
  cp /etc/skel/.bashrc .
fi

if [ -f /etc/skel/.bash_profile ] ; then
  cp /etc/skel/.bash_profile .
fi

if [ -f /etc/skel/.bash_logout ] ; then
  cp /etc/skel/.bash_logout .
fi

/bin/rm -f ~/menv/.lock

echo "Uninstalling menv done, please exit the terminal"
