#!/bin/bash
# (C) 2013-2014 David 'Mokon' Bond, All Rights Reserved

echo "Uninstalling menv"
lockfile -r-1 $menv_dir/.lock

spushd .

cd ~

menv_version ignore
menv_target login &> /dev/null # So we have the aliases etc in the menv arrays.

menv_target_children uninstall

if_symlink_rm $bashrc
if_symlink_rm $bash_profile
if_symlink_rm $bash_logout

if_symlink_rm ~/todo
if_symlink_rm ~/cloud
if_symlink_rm ~/docs
if_symlink_rm ~/pics
  
echo "Saving the menv backup and local directories."
$MV $menv_backup_dir ~
$MV $menv_local_dir ~

echo "Deleting the menv directory."
$RM -rf $menv_dir

spopd
 
for menv_export in "${menv_exports[@]}" ; do
  unset "$( echo $menv_export | cut -f1 -d "=")"
done
unset menv_exports

for menv_alias in "${menv_aliases[@]}" ; do
  unalias "$( echo $menv_alias | cut -f 1 -d "=")"
done
unset menv_aliases

for menv_func in "${menv_funcs[@]}" ; do
  unset $menv_func
done
unset menv_funcs

/bin/rm -f ~/menv/.lock

echo "Uninstalling menv done"

