#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

echo "Updating menv"

menv_target_children update

ping -c1 -W1 github.com &> /dev/null
if [ $? ]; then
  if [ "$(menv_version get)" == "$(menv_latest_version)" ] ; then
    echo "menv is up to date."
    return 0
  fi
else
  echo "Git Hub not reachable. Could not update."
  return -1
fi

pushd .

menv_uninstall
bash <(curl -s https://raw.github.com/Mokon/menv/master/core/remote_install)

popd

echo "Updating menv done"

