#!/bin/bash
# (C) 2013 David 'Mokon' Bond, All Rights Reserved

echo "Updating menv"

ping -c1 -W1 github.com &> /dev/null
if [ $? ]; then
  menvs=0 # TODO 

  if [[ $menvs ]] ; then
    echo "menv is up to date."
    return 0
  fi
else
  echo "Git Hub not reachable. Could not update."
  return -1
fi

pushd .

$menv_dir/uninstall
bash <(curl -s https://raw.github.com/Mokon/menv/master/core/remote_install)

popd

