#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved
# requirements pkg_mgmt == dnf

function dnf_what_provides {
  echo "exzact:"
  sudo dnf whatprovides "$@"

  echo "fuzzy:"
  sudo dnf whatprovide "*/`which "$@"`"
}
