#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved

if [ $PKG_TYPE == "dpkg" ] ; then 
  alias dpkg_what_provides="sudo dpkg --search"
  #alias dpkg_what_provides="sudo dpkg-query -S"
  alias dpkg_provides_what="sudo dpkg-query -L"
fi
