#!/bin/bash
# (C) 2013-2019 David 'Mokon' Bond, All Rights Reserved
# requirements pkg_type == rpm

alias rpm_list_deps="rpm -qpR"

function rpm_what_provides {
  echo "exzact:"
  rpm -q --whatprovides "$@"

  echo "which:"
  rpm -q --whatprovides `which "$@"`
}

alias largest_pkgs="rpm -qa --queryformat '%10{size} - %-25{name} \t %{version}\n' | sort -n"
alias installed_pkgs_size="largest_pkgs | awk '{ sum += $1 } END { print sum }'"
