#!/bin/bash
# (C) 2013-2015 David 'Mokon' Bond, All Rights Reserved

if [ $PKG_TYPE == "rpm" ] ; then
  menv_alias rpm_list_deps="rpm -qpR"

  menv_function rpm_what_provides
  function rpm_what_private {
    echo "exzact:"
    rpm -q --whatprovides "$@"

    echo "which:"
    rpm -q --whatprovides `which "$@"`
  }

  menv_alias largest_pkgs="rpm -qa --queryformat '%10{size} - %-25{name} \t %{version}\n' | sort -n"
  menv_alias installed_pkgs_size="largest_pkgs | awk '{ sum += $1 } END { print sum }'"
fi
